### ISSUE TITLE
admob causing crashes on most of the device in android

### ISSUE THREAD

**Issue by alihassan143** [googleads/googleads-mobile-flutter#1005]
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at io.flutter.plugins.googlemobileads.h0.onMethodCall(Unknown Source:601)
	at w9.k$a.a(Unknown Source:17)
	at k9.c.l(Unknown Source:18)
	at k9.c.m(Unknown Source:40)
	at k9.c.i(Unknown Source:0)
	at k9.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:322)
```

### Admob version
`google_mobile_ads: ^4.0.0`

**Comment by alihassan143** [comment]
![Screenshot 2024-02-16 at 9 36 38 AM](https://github.com/googleads/googleads-mobile-flutter/assets/71745182/08eb7cd0-9dc0-4ef0-b41f-b56c23c5c866)
this is causing lots of crashes

**Comment by alihassan143** [comment]
the crash is happeining when loading open add
that behaviour cannot visible on android 14 but on
![Screenshot 2024-02-16 at 11 10 38 AM](https://github.com/googleads/googleads-mobile-flutter/assets/71745182/fb1746a1-d429-4ee6-abd9-aef1368f93de)
 android 10 and lower device you can see this issue 
 
 
 ### how to reproduce this 
[Open add admob Example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/app_open_example)

**Comment by malandr2** [comment]
Hey @alihassan143, a few questions:

The Crashlytics screenshot doesn't offer much information. Can you share a more detailed screenshot?

Does the crash _only_ happen on version `4.0.0`?
Can you reproduce it using our [Android  app open example](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/AppOpenExample)?

Does only it occur with the App Open example? Does it happen on app launch? Ad display? 
Can you please provide clear steps to reproduce? Thanks

**Comment by stesancri** [comment]
Hi @malandr2, I've had the same experience the OP is having in my app for a couple of times.

 I have two ads in my app:
  - The BannerAd in the home page loaded fine.
  - The NativeAd I load inside a ListView.builder crashed the app as soon as it was loaded

Package: `google_mobile_ads: ^4.0.0`

Device: `OnePlus6T (OnePlus6T)`

OS: `Android 11 (SDK 30)`

Type: `java.lang.NullPointerException`

```
Exception java.lang.NullPointerException:
  at com.sclh.sonar.ListTileNativeAdFactory.createNativeAd (ListTileNativeAdFactory.java)
  at io.flutter.plugins.googlemobileads.FlutterNativeAd.onNativeAdLoaded (FlutterNativeAd.java)
  at io.flutter.plugins.googlemobileads.FlutterNativeAdLoadedListener.onNativeAdLoaded (FlutterNativeAdLoadedListener.java)
  at com.google.android.gms.internal.ads.zzbsk.zze (zzbsk.java)
  at com.google.android.gms.internal.ads.zzbhb.zzbJ (zzbhb.java)
  at com.google.android.gms.internal.ads.zzaun.onTransact (zzaun.java)
  at android.os.Binder.transact (Binder.java:1054)
  at m.ajj.ba (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:8)
  at com.google.android.gms.ads.internal.formats.client.al.e (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:9)
  at com.google.android.gms.ads.nonagon.ad.nativead.af.run (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:63)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at m.awy.a (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
  at com.google.android.gms.ads.internal.util.f.a (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:2)
  at m.awy.dispatchMessage (:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
  at android.os.Looper.loop (Looper.java:233)
  at android.app.ActivityThread.main (ActivityThread.java:8068)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:631)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)
  ```
  
  Hope it helps
  Thanks

**Comment by malandr2** [comment]
Hey @stesancri, looking at your stack trace, your issue looks to be unrelated. Are you following https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7? Looks like your crash is happening in a `ListTileNativeAdFactory` class, which is not in the `google_mobile_ads` flutter plugin. It appears to be an implementation issue. As a next step I recommend debugging your `createNativeAd` method. 

If you have any follow-ups, please create a new issue in GitHub as it's ultimately unrelated to OP's issue. Thanks!

**Comment by mregnauld** [comment]
Not sure at all, but could it be related to [this](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)?

As soon as I migrate my code following that guide, the `google_mobile_ads` package makes my app crash, so I wonder if there is a link or not...

**Comment by malandr2** [comment]
Closing due to inactivity from OP
