### ISSUE TITLE
[iOS] Lexical or Preprocessor Issue (Xcode): 'GoogleMobileAds/GoogleMobileAds.h' file not found

### ISSUE THREAD

**Issue by triadats** [googleads/googleads-mobile-flutter#1006]
### [REQUIRED] Step 1: Describe your environment

System: MacOS: 12.7.3 (MacBook Pro)
Xcode: Version 14.2 (14C18)
Flutter: 3.19.0
Dart: 3.3.0

Error on iOS Simulator and physical device

Quick Flutter Doctor Review:
```
[✓] Flutter (Channel stable, 3.19.0, on macOS 12.7.3 21H1015 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Connected device (3 available)
[✓] Network resources
```
## Plugin Version

All of my dependencies: (pubspec.yaml)
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
```

### [REQUIRED] Step 2: Describe the problem

Running the app fails on error below (file not found)
Error in VSCode and Xcode

My changes:
Upgraded flutter and dart to latest
Created a new blank app to test and it fails as well

Info:
All other dependencies are working properly
- firebase (core, auth, cloud)
- slidable
- svg
- intl
- fonts
all working

Quick reference:
The app will run without google_mobile_ads (pubspec.yaml)
If the app is running you can add google_mobile_ads in and it stays running but missing dependencies that load on full restart
If closed while running with google_mobile_ads added back in and fully restarted it fails again.

Steps to Reproduce:

Run: flutter run -v or select run/debug

**Expected results:**
Prior to this week the app ran perfectly

**Actual results:** 
Details below

<details>
  <summary>Logs</summary>
Build Log:

```
[  +15 ms] Failed to build iOS app
[   +3 ms] Lexical or Preprocessor Issue (Xcode): 'GoogleMobileAds/GoogleMobileAds.h' file not found

/Users/mine/.pub-cache/hosted/pub.dev/google_mobile_ads-4.0.0/ios/Classes/NativeTemplates/GoogleAdsMobileIosNativeTemplates/GADTTemplateView.h:14:8
           
[   +7 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Pro.
[  +13 ms] "flutter run" took 44,500ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:811:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +118 ms] ensureAnalyticsSent: 115ms



```
```
flutter analyze
Analyzing ios_ads_test...                                               

   info • Don't invoke 'print' in production code • lib/main.dart:76:7 • avoid_print

1 issue found. (ran in 4.0s)
```
Print added just for testing purposed

```
Full flutter doctor:
[✓] Flutter (Channel stable, 3.19.0, on macOS 12.7.3 21H1015 darwin-x64, locale en-US)
    • Flutter version 3.19.0 on channel stable at /Users/jeffbeck/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (4 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jeffbeck/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.15.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 2543658D-35F5-45F9-8E3F-B18644F917E6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.7.3 21H1015 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by SinapseVB** [comment]
I have the same error.

**Comment by marcsanny** [comment]
Same here :(

**Comment by triadats** [comment]
@ marcsanny
I wish I could say that worked for me.
I have tried everything including 
-rebuilding the pod file
-completely deleting the iOS folder content
-even building a new project

Still getting the same error on all accounts.

I greatly appreciate the reply and comment

**Comment by malandr2** [comment]
@triadats I cannot reproduce the issue you are experiencing. I am able to run our [sample projects](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob) as expected? Are you able to?

It's possible it may be an issue with your pods setup? Does the error not happen using the previous `google_mobile_ads` version? (`^3.1.0`)

**Comment by triadats** [comment]
Even cleared the pods cache with the below and getting the same message still

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
```

**Comment by malandr2** [comment]
https://github.com/googleads/googleads-mobile-unity/issues/543 is a similar issue that was able to be resolved, albeit from a Unity developer.

**Comment by AnthonyKalampogias** [comment]
Hey, I am also experiencing this issue with the google_mobile_ads package

### I face the same issue with google maps

When I try to `flutter build ios` I get the same error
`Lexical or Preprocessor Issue (Xcode): 'GoogleMobileAds/GoogleMobileAds.h'
file not found
/Users/.../.pub-cache/hosted/pub.dev/google_mobile_ads-4.0.0/ios/Clas
ses/NativeTemplates/GoogleAdsMobileIosNativeTemplates/GADTTemplateView.h:14:
8`

System
- macOS: 13.5.1 
- xCode:  15.2
- Flutter version 3.19.1
- Dart version 3.3.0
- CocoaPods version 1.15.1

```
[✓] Flutter (Channel stable, 3.19.1, on macOS 13.5.1 22G90 darwin-arm64,
    locale en-GR)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.2)
[✓] Connected device (2 available)
[✓] Network resources
```

In the project I first encountered this issue has a lot of packages but at first I was using 
google_mobile_ads: ^2.3.0

Many suggested to try on a new project but no luck there I get the same issue, I also tried one of the examples from the google ads repo and I get the same issue...
I even tried from Codemagic to build my app and again I get the same issue...

I have been searching for a solution for over 2 weeks now this is becoming extremely frustrating, please help me out on this. If you need anything from my files let me know and I'll do my best to reply as soon as possible.

## Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'MLKitVision', :podspec => 'MLKitVision.podspec.json'
  pod 'MLKitCommon', :podspec => 'MLKitCommon.podspec.json'

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  # Ensure pods also use the minimum deployment target set above
  # https://stackoverflow.com/a/64385584/436422
  puts 'Determining pod project minimum deployment target'

  pods_project = installer.pods_project
  deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
  deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
  minimum_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }

  puts 'Minimal deployment target is ' + minimum_deployment_target
  puts 'Setting each pod deployment target to ' + minimum_deployment_target

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      #config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings[deployment_target_key] = minimum_deployment_target
    end
  end
end
```


## Dependencies from pubspec.yaml
I left some other google packages just in case that might have to do anything with my problem because I face the same issue with google maps
```
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_messaging: ^14.2.6
  firebase_analytics: ^10.1.5
  firebase_crashlytics: ^3.0.16
  connectivity_plus: ^3.0.3
  intl: any
  google_fonts: ^4.0.3
  firebase_storage: ^11.0.16
  google_sign_in: ^6.1.5
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  ...
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  firebase_ui_firestore: ^1.5.6
  google_mobile_ads: ^2.3.0

flutter_launcher_icons:
...


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
