### ISSUE TITLE
java.lang.VerifyError: Verifier rejected class

### ISSUE THREAD

**Issue by LondonX** [googleads/googleads-mobile-flutter#1028]
## Plugin Version

4.0.0

### [REQUIRED] Step 2: Describe the problem
My Android app run with some ads mediations in previous releases.
After upgrading mediations SDKs, It cannot make AdRequest anymore and crashes.
After I remove all the mediations, it works again.
The crash log is attached below.

## Steps to Reproduce
1. Add `implementation 'com.google.ads.mediation:facebook:+'` in the dependencies of app's `build.gradle`.
2. `flutter run --profile`
3. Request any type of ads from flutter
4. Crash with the `java.lang.VerifyError: Verifier rejected class` error

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
E/AndroidRuntime(27393): FATAL EXCEPTION: main
E/AndroidRuntime(27393): Process: com.LondonX.monetization_kit_example, PID: 27393
E/AndroidRuntime(27393): java.lang.VerifyError: Verifier rejected class io.flutter.plugins.googlemobileads.FlutterAdManagerAdRequest: com.google.android.gms.ads.admanager.AdManagerAdRequest io.flutter.plugins.googlemobileads.FlutterAdManagerAdRequest.asAdManagerAdRequest(java.lang.String) failed to verify: com.google.android.gms.ads.admanager.AdManagerAdRequest io.flutter.plugins.googlemobileads.FlutterAdManagerAdRequest.asAdManagerAdRequest(java.lang.String): [0x5] register v0 has type Precise Reference: com.google.android.gms.ads.admanager.AdManagerAdRequest$Builder but expected Reference: com.google.android.gms.ads.AdRequest$Builder (declaration of 'io.flutter.plugins.googlemobileads.FlutterAdManagerAdRequest' appears in /data/app/~~uVbm_efjZU1cWgD6ytiN_Q==/com.LondonX.monetization_kit_example-ZDeiDHbLiVChzTAi55rLWA==/base.apk!classes2.dex)
E/AndroidRuntime(27393): 	at io.flutter.plugins.googlemobileads.FlutterAdManagerAdRequest$Builder.build(FlutterAdManagerAdRequest.java:62)
E/AndroidRuntime(27393): 	at io.flutter.plugins.googlemobileads.AdMessageCodec.readValueOfType(AdMessageCodec.java:335)
E/AndroidRuntime(27393): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:340)
E/AndroidRuntime(27393): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:434)
E/AndroidRuntime(27393): 	at io.flutter.plugins.googlemobileads.AdMessageCodec.readValueOfType(AdMessageCodec.java:406)
E/AndroidRuntime(27393): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:340)
E/AndroidRuntime(27393): 	at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:49)
E/AndroidRuntime(27393): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:265)
E/AndroidRuntime(27393): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(27393): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(27393): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(27393): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(27393): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27393): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(27393): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(27393): 	at android.app.ActivityThread.main(ActivityThread.java:8248)
E/AndroidRuntime(27393): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27393): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(27393): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process (27393): Sending signal. PID: 27393 SIG: 9
Lost connection to device.

Exited.
```

</details>

<details>
  <summary>flutter analyze</summary>

```
Analyzing monetization_kit...                                           
No issues found! (ran in 4.4s)
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1.1 23B81 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.19.3 on channel stable at /Users/london/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (12 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/london/Library/Android/sdk/
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/london/Library/Android/sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 26111FDF6002Q4 • android-arm64  • Android 14 (API 34)
    • macOS (desktop)  • macos          • darwin-x64     • macOS 14.1.1 23B81
      darwin-x64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome
      122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by malandr2** [comment]
Hey @LondonX, I tried to reproduce using the steps provided in our [banner_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/banner_example) and could not reproduce (ad loaded successfully). Are you able to reproduce in our `banner_example` project?

Initial look at the crash log there could be a mismatch between `AdRequest` and `AdManagerAdRequest`, can you confirm you're using only one type?

**Comment by LondonX** [comment]
Thanks for the reply
After testing on `banner_example`, I found the issue is caused by these mediations which using higher version of `com.google.android.gms:play-services-ads`
```
com.google.ads.mediation:pangle:+
com.google.ads.mediation:ironsource:+
```
they are using their own repos
```gradle
rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifact.bytedance.com/repository/pangle/' }
        maven { url 'https://android-sdk.is.com/' }
        maven { url 'https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea' }
        maven { url 'https://cboost.jfrog.io/artifactory/chartboost-ads/' }
    }
}
```
here is part of current dependencies trees
```
|    +--- com.google.ads.mediation:pangle:+ -> 5.8.0.9.0
|    |    +--- com.pangle.global:ads-sdk:5.8.0.9
|    |    |    +--- com.pangle.global:crash_monitor:1.3.8.13
|    |    |    |    +--- com.pangle.global:encryptor:0.0.9-rc.2-private
|    |    |    |    \--- androidx.annotation:annotation:1.3.0 -> 1.7.1 (*)
|    |    |    +--- com.pangle.global:metasec_pgl:1.0.0.5-rc.4
|    |    |    +--- com.pangle.global:gecko:1.0.0.3-rc.13
|    |    |    \--- androidx.browser:browser:1.6.0-alpha02 (*)
|    |    +--- androidx.annotation:annotation:1.5.0 -> 1.7.1 (*)
|    |    \--- com.google.android.gms:play-services-ads:23.0.0 (*)
```
```
|    +--- com.google.ads.mediation:ironsource:+ -> 7.9.0.0
|    |    +--- com.ironsource.sdk:mediationsdk:7.9.0
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.8.0 -> 1.8.21 (*)
|    |    +--- androidx.annotation:annotation:1.5.0 -> 1.7.1 (*)
|    |    +--- com.google.android.gms:play-services-ads:23.0.0 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.20 (*)
```
it shows only they using `com.google.android.gms:play-services-ads:23.0.0` while other mediations are using version `21` or `22` in my project.

After I downgrade the version to 
```
com.google.ads.mediation:pangle:5.8.0.7.0
com.google.ads.mediation:ironsource:7.8.1.1
```
the issue solved.

**Comment by felipecastrosales** [comment]
hey, did you manage to mediate for iOS? I'm still having problems. Currently it's: `Library 'BURelyFoundationGlobalAFN' not found`; I don't know what I need do to work.

**Comment by LondonX** [comment]
No I didn't, it looks like caused by too low `Minimal Deployments` config in Xcode? (not for sure)
May help you if you can share more logs of `pod install`.
