### ISSUE TITLE
google_mobile_ads 5.2.0 not compatible with cocoa pod IronSourceAdMobAdapter (= 4.3.58.0) 

### ISSUE THREAD

**Issue by lpc49** [googleads/googleads-mobile-flutter#1211]
## Plugin Version

plugin version: google_mobile_ads: 5.2.0
platform: iOS

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
flutter dependencies in pubspec.yaml:
```
google_mobile_ads: ^5.2.0
ironsource_mediation: ^3.0.0
```

Pod dependencies in ios/Podfile:
```
pod 'IronSourceSDK','8.4.0.0'
pod 'IronSourceAdMobAdapter','4.3.58.0'
```

3. within folder ios, run `pod update`.

4. **Expected results:** run without error
**Actual results:** 
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    IronSourceAdMobAdapter (= 4.3.58.0) was resolved to 4.3.58.0, which depends on
      Google-Mobile-Ads-SDK (= 11.11.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 5.2.0, which depends on
      Google-Mobile-Ads-SDK (~> 11.10.0)
```

<details>
  <summary>Logs</summary>

flutter run --verbose
```
[        ]                                                                                                                      
[  +76 ms] Found plugin google_mobile_ads at /Users/lpc49/.pub-cache/hosted/pub.dev/google_mobile_ads-5.2.0/
[  +13 ms] Found plugin ironsource_mediation at /Users/lpc49/.pub-cache/hosted/pub.dev/ironsource_mediation-3.0.0/
[  +87 ms] Found plugin webview_flutter at /Users/lpc49/.pub-cache/hosted/pub.dev/webview_flutter-4.9.0/
[   +2 ms] Found plugin webview_flutter_android at /Users/lpc49/.pub-cache/hosted/pub.dev/webview_flutter_android-3.16.9/
[   +5 ms] Found plugin webview_flutter_wkwebview at /Users/lpc49/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.16.2/
[  +37 ms] executing: which pod
[  +24 ms] executing: pod --version
[+1939 ms] 1.16.2
[   +2 ms] Running pod install...
[+1920 ms] Running pod install... (completed in 1,900ms)
[        ] CocoaPods' output:
           ↳
[        ]       Preparing
           
               Analyzing dependencies
           
               Inspecting targets to integrate
                 Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
           
               Fetching external sources
               -> Fetching podspec for `Flutter` from `Flutter`
               -> Fetching podspec for `google_mobile_ads` from `.symlinks/plugins/google_mobile_ads/ios`
               -> Fetching podspec for `ironsource_mediation` from `.symlinks/plugins/ironsource_mediation/ios`
               -> Fetching podspec for `webview_flutter_wkwebview` from `.symlinks/plugins/webview_flutter_wkwebview/darwin`
           
               Resolving dependencies of `Podfile`
                 CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_7_7_b.txt exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/7/7/b/IronSourceSDK/8.4.0.0/IronSourceSDK.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_c_1_5.txt exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/c/1/5/IronSourceAdMobAdapter/4.3.58.0/IronSourceAdMobAdapter.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_5_9_a.txt exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/5/9/a/Google-Mobile-Ads-SDK/11.12.0/Google-Mobile-Ads-SDK.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_4_2_c.txt exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/4/2/c/FlutterMacOS/3.16.0/FlutterMacOS.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/7/7/b/IronSourceSDK/8.4.0.0/IronSourceSDK.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/c/1/5/IronSourceAdMobAdapter/4.3.58.0/IronSourceAdMobAdapter.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/7/7/b/IronSourceSDK/8.4.0.0/IronSourceSDK.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/5/9/a/Google-Mobile-Ads-SDK/11.10.0/Google-Mobile-Ads-SDK.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: all_pods_versions_7_e_f.txt exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/7/e/f/GoogleUserMessagingPlatform/2.7.0/GoogleUserMessagingPlatform.podspec.json exists! Returning local because checking is only performed in repo update
                 CDN: trunk Relative path: Specs/5/9/a/Google-Mobile-Ads-SDK/11.11.0/Google-Mobile-Ads-SDK.podspec.json exists! Returning local because checking is only performed in repo update
               [!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
                 In Podfile:
                   IronSourceAdMobAdapter (= 4.3.58.0) was resolved to 4.3.58.0, which depends on
                     Google-Mobile-Ads-SDK (= 11.11.0)
           
                   google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 5.2.0, which depends on
                     Google-Mobile-Ads-SDK (~> 11.10.0)
           
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
               <internal:kernel>:90:in `tap'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:700:in `attempt_to_filter_existing_spec'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/resolver.rb:94:in `resolve'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:422:in `analyze'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:162:in `install!'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/bin/pod:25:in `load'
               /Users/lpc49/.rvm/rubies/ruby-3.3.3/bin/pod:25:in `<main>'
               /Users/lpc49/.rvm/gems/ruby-3.3.3/bin/ruby_executable_hooks:22:in `eval'
               /Users/lpc49/.rvm/gems/ruby-3.3.3/bin/ruby_executable_hooks:22:in `<main>'
           
[   +9 ms] Error: Error running pod install
[   +4 ms] "flutter run" took 24,082ms.
```

flutter analyze
```
Analyzing ios...                                                        
No issues found! (ran in 0.7s)
```

flutter doctor -v:
```
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.7.1 23H222 darwin-x64, locale en-US)
    • Flutter version 3.24.5 on channel stable at /Users/lpc49/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (17 hours ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (2 available)
    • iPhone (mobile) •XXXXX • ios        • iOS 15.8.3 19H386
    • macOS (desktop)          • macos                                    • darwin-x64 • macOS 14.7.1 23H222 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by lpc49** [comment]
What I tried (did not solve the issue):
- `flutter clean`, `flutter pub get`, `flutter upgrade`, delete Pod.lock file, `pod deintegrate`, `pod install --repo-update`
- explicitly set `platform :ios, '13.0'` within Podfile
- explicitly downgrading `IronSourceSDK` and `IronSourceAdMobAdapter` to earlier versions within Podfile

**Comment by malandr2** [comment]
Hi @lpc49, it's possible that not all adapters will be compatible with our release. If you need to update the iOS SDK for your case, you are able to so in the [podspec](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/ios/google_mobile_ads.podspec#L18) to 11.11.0.

**Comment by lpc49** [comment]
Thank you @malandr2 ! 
FYI While I wait for the next release as a proper solution, the workaround you suggested in a prior message (updating the version directly in the podspec file) seems to work for me as a temporary solution.
Best
Lucien
