### ISSUE TITLE
Android crash : java.lang.IllegalStateException - The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by Tom3652** [googleads/googleads-mobile-flutter#1214]
## Plugin Version

`google_mobile_ads: ^5.2.0`

## Steps to Reproduce

I have a live app with few thousands of daily active users. 
Some of them only on Android received a crash from this package (i have the reporting in Firebase Crashlytics) but i have never encountered this bug by testing the app in `debug` or `release` mode unfortunately so i can't reproduce it but maybe the stack trace will tell you something...

Note : i can provide the whole stack trace if needed, i am simply showing the main crash error here.

**Expected results:** 
The app should not crash

**Actual results:** 
The app is crashing

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.RuntimeException: Unable to stop activity {com.myappname/com.google.android.gms.ads.AdActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5266)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5234)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5303)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:202)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:174)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
 Caused by java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5355)
       at android.view.ViewGroup.addView(ViewGroup.java:5175)
       at com.google.android.gms.ads.internal.overlay.zzg.p(com.google.android.gms:play-services-ads@@23.5.0:96)
       at com.google.android.gms.ads.internal.overlay.zzg.y(com.google.android.gms:play-services-ads@@23.5.0:109)
       at com.google.android.gms.ads.internal.overlay.zzg.k(com.google.android.gms:play-services-ads@@23.5.0:36)
       at com.google.android.gms.ads.internal.overlay.client.a.bV(:com.google.android.gms.policy_ads_fdr_dynamite@243799217@243799205017.692206067.692206067:131)
       at m.anx.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@243799217@243799205017.692206067.692206067:21)
       at android.os.Binder.transact(Binder.java:1064)
       at com.google.android.gms.internal.ads.zzayc.zzdc(com.google.android.gms:play-services-ads-base@@23.5.0:2)
       at com.google.android.gms.internal.ads.zzbte.zzu(com.google.android.gms:play-services-ads-lite@@23.5.0:2)
       at com.google.android.gms.ads.AdActivity.onStop(com.google.android.gms:play-services-ads-lite@@23.5.0:1)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1496)
       at android.app.Activity.performStop(Activity.java:8347)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5254)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5234)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5303)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:202)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:174)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-x64, locale fr-FR)
    • Flutter version 3.24.5 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 15.1.1 24B91 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 131.0.6778.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by malandr2** [comment]
Hi @Tom3652, because this is only happening on Android, we can deduce it's not a Flutter issue so can you create a thread in the [AdMob Developer forum](https://groups.google.com/g/google-admob-ads-sdk)? This is is the best way to have your issue properly troubleshooted.

Closing this out - thanks!
