### ISSUE TITLE
java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.🐛 

### ISSUE THREAD

**Issue by claptv** [googleads/googleads-mobile-flutter#182]
## Bug report

**Describe the bug**

```
java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.** 
```

occurs right after a BannerAd is loaded on SamSung Galaxy Tab 4 running on Android version 4.4.2. 

This problem is not happening on the SamSung Galaxy S9+ and the Simulator and the BannerAd is displayed well.

```console
BannerAd loaded.
E/flutter (15370): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.
E/flutter (15370): 	at android.media.ImageReader.nativeImageSetup(Native Method)
E/flutter (15370): 	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:292)
E/flutter (15370): 	at android.media.ImageReader.acquireNextImage(ImageReader.java:338)
E/flutter (15370): 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:242)
E/flutter (15370): 	at io.flutter.embedding.android.FlutterImageView.acquireLatestImage(FlutterImageView.java:175)
E/flutter (15370): 	at io.flutter.embedding.android.FlutterView.acquireLatestImageViewFrame(FlutterView.java:1091)
E/flutter (15370): 	at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:810)
E/flutter (15370): 	at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:982)
E/flutter (15370): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (15370): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter (15370): 	at android.os.Looper.loop(Looper.java:131)
E/flutter (15370): 	at android.app.ActivityThread.main(ActivityThread.java:5602)
E/flutter (15370): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter (15370): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter (15370): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/flutter (15370): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/flutter (15370): 	at dalvik.system.NativeStart.main(Native Method)
```

### Steps to reproduce

1. Create a BannerAd and load.
2. Build AdWidget with the BannerAd created at Step 1.

### Expected behavior

A BannerAd is expected to be display where the AdWidget is located.
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
 [✓] Flutter (Channel beta, 2.2.0-10.1.pre, on Mac OS X 10.15.7 19H512 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!


```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0-211.6.beta
Flutter SDK 2.2.0-10.1.pre
clap_tv 0.4.18

dependencies:
- better_player 0.0.64 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection]
- cloud_firestore 1.0.5 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- device_info 2.0.0 [flutter device_info_platform_interface]
- email_validator 2.0.1
- firebase_auth 1.1.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 5.0.0+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_widget_from_html_core 0.6.0 [csslib flutter html]
- font_awesome_flutter 9.0.0 [flutter]
- google_mobile_ads 0.12.1+1 [meta flutter]
- provider 5.0.0 [collection flutter nested]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- video_player 2.1.0 [meta video_player_platform_interface video_player_web flutter flutter_test]
- wakelock 0.5.1 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.5 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- csslib 0.17.0 [source_span]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_inappwebview 5.3.1 [flutter]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- visibility_detector 0.2.0 [flutter]
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]

```

</details>

---

**Comment by maheshmnj** [comment]
Hi @claptv, Thanks for reporting the issue, could you please try using the latest `google_mobile_ads: ^0.13.3` on the latest stable channel and see if this fixes the issue, I was able to play the banner ad on Xiaomi k20 Pro (Android 11).

>occurs right after a BannerAd is loaded on SamSung Galaxy Tab 4 running on Android version 4.4.2.

Since you are having the issue only on a particular device I suspect this to be device specific. 

<details>
<summary>output</summary>

<img src="https://user-images.githubusercontent.com/31410839/128828678-98e982fa-69a9-4150-bb04-fd69695277f3.png" width="350">

</details>
