### ISSUE TITLE
java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd

### ISSUE THREAD

**Issue by zenkog** [googleads/googleads-mobile-flutter#199]
This is a strange error and I have tried many things to fix it for the last 3 days without any success.

Please note that it was WORKING and the App is live for more than a few months now, so all the credentials are correct and I have re-checked it many times. 

So I don't know exactly what happened but I have no other place to find solution that I finally post an issue here. I hope someone could help to give me pointers.

The moment `rewardedAd.load()` is called, the app crashed with error message as follows:
```
E/AndroidRuntime(27180): FATAL EXCEPTION: main
E/AndroidRuntime(27180): Process: com.me.app, PID: 27180
E/AndroidRuntime(27180): java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
E/AndroidRuntime(27180): 	at io.flutter.plugins.googlemobileads.FlutterRewardedAd.createRewardedAd(FlutterRewardedAd.java:154)
E/AndroidRuntime(27180): 	at io.flutter.plugins.googlemobileads.FlutterRewardedAd.load(FlutterRewardedAd.java:95)
E/AndroidRuntime(27180): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:330)
E/AndroidRuntime(27180): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(27180): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(27180): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(27180): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(27180): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(27180): 	at android.os.Looper.loop(Looper.java:197)
E/AndroidRuntime(27180): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(27180): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27180): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(27180): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process (27180): Sending signal. PID: 27180 SIG: 9
```

In my code:
`MobileAds.instance.initialize()` is called in `main.dart` and once the initialization is done the `RewardedAd` is being initialized like this:

```
_rewardedAd = RewardedAd(
          adUnitId: AdManager.rewardedAdUnitId,
          listener: AdListener(
            onRewardedAdUserEarnedReward: (RewardedAd ad, RewardItem reward) {
              print('Rewarded Ad successful: $ad reward: $reward');
              // Give reward to user
            },
            onAdLoaded: (Ad ad) {
              setState(() {
                isAdsLoading = false;
              });
            },
            onAdFailedToLoad: (Ad ad, LoadAdError error) {
              print('Error Rewarded Video Ad failed to load: $error');
            },
          ),
          request: AdRequest())
        ..load();
```

If I remove the `..load()` it won't crash but it won't ever load. Once again, this didn't crash before.

What I have done to fix this:
1. I have rechecked all the credentials: App ID and Ad unit Id are all correct.
2. Go through the documentations again to make sure my `AndroidManifest.xml` are correctly set. 
3. Tried both versions 0.12.1+1 and 0.11.0+4
4. Tried both debug and release mode
5. Tried both in Android Virtual Device and real device.
6. There are many others that I don't remember anymore.

Note: The live version is working fine. And I have tried to upload the app to Closed Testing release, but it still crashed.

## Plugin Version

version ^0.12.1+1

## Steps to Reproduce

I'm not sure how to reproduce this. Because everything was working and the app is live without problems until 3 days ago.

1. Initialize: `MobileAds.instance.initialize()`
2. Initialize RewardedAds
3. Call `rewardedAds.load()`
**Expected results:** 
Shouldn't crash and shows the ad

**Actual results:** 
It crashes, the app closed and there was no exception caught except the `FATAL EXCEPTION` message

<details>
  <summary>Logs</summary>

It is a long log, so I only include the error part here, but you can read all the [full log here](https://drive.google.com/file/d/1-XAFRklfOyqTNj9O-ByolsjiYgFDj2eM/view?usp=sharing)

```
[  +35 ms] E/AndroidRuntime(31757): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(31757): Process: com.me.app, PID: 31757
[        ] E/AndroidRuntime(31757): java.lang.InstantiationError:
com.google.android.gms.ads.rewarded.RewardedAd
[        ] E/AndroidRuntime(31757): 	at
io.flutter.plugins.googlemobileads.FlutterRewardedAd.createRewardedAd(FlutterRewardedAd.java:154)
[        ] E/AndroidRuntime(31757): 	at
io.flutter.plugins.googlemobileads.FlutterRewardedAd.load(FlutterRewardedAd.java:95)
[        ] E/AndroidRuntime(31757): 	at
io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:330)
[        ] E/AndroidRuntime(31757): 	at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/AndroidRuntime(31757): 	at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/AndroidRuntime(31757): 	at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[        ] E/AndroidRuntime(31757): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/AndroidRuntime(31757): 	at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/AndroidRuntime(31757): 	at android.os.Looper.loop(Looper.java:197)
[        ] E/AndroidRuntime(31757): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
[        ] E/AndroidRuntime(31757): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(31757): 	at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[        ] E/AndroidRuntime(31757): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
[  +33 ms] I/Process (31757): Sending signal. PID: 31757 SIG: 9
[ +261 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] executing: /Volumes/ME/Applications/Android/sdk/platform-tools/adb -s 5a53414a33573398 forward
--list
[  +11 ms] Exit code 0 from: /Volumes/ME/Applications/Android/sdk/platform-tools/adb -s 5a53414a33573398
forward --list
[        ] 5a53414a33573398 tcp:59154 tcp:34485
[   +1 ms] executing: /Volumes/ME/Applications/Android/sdk/platform-tools/adb -s 5a53414a33573398 forward
--remove tcp:59154
[  +13 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/com.me.app/code_cache/my_appCGPZRY/my_app/)
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] executing: /Volumes/ME/Applications/Android/sdk/platform-tools/adb -s 5a53414a33573398 forward
--list
[  +16 ms] Exit code 0 from: /Volumes/ME/Applications/Android/sdk/platform-tools/adb -s 5a53414a33573398
forward --list
[   +2 ms] "flutter run" took 140,682ms.
[   +4 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing my_app...                                           
No issues found! (ran in 6.1s)
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/ME/development/flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Volumes/ME/Applications/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Volumes/ME/Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (3 available)
    • SM G960U1 (mobile)  • 5a5341                         • android-arm64  • Android 10 (API 29)
    • ME iPho (mobile) • b3ebbe938628 • ios            • iOS 14.4.2
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome
      90.0.4430.85

• No issues found!
```

</details>

**Comment by blasten** [comment]
@jjliu15 was `com.google.android.gms.ads.rewarded.RewardedAd` ever an interface or abstract class?

**Comment by zenkog** [comment]
Hi, do we have any update here?

**Comment by zenkog** [comment]
Thanks for the reply.

If not mistaken it was version 0.11.0+4

And for the `build.gradle`, did you mean `app/build.gradle`?

<details>
<summary>build.gradle</summary>
```
apply plugin: 'com.android.application'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('keystore.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.me.app"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {

        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    ndkVersion "22.0.6917172"

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            dependencies {
                implementation 'android.arch.lifecycle:common-java8:1.1.1'
                implementation 'android.arch.lifecycle:extensions:1.1.1'
            }
            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'com.google.android.gms:play-services-ads:19.8.0'
    implementation 'com.google.android.gms:play-services-basement:17.6.0'
}

apply plugin: 'com.google.gms.google-services'
```
</details>

> @blasten RewardedAd was made abstract in version 20.0.0 of GMASDK. However the plugin is still at [19.7.0](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/android/build.gradle#L35) which is not abstract.
> 
> I also want to note that `createRewardedAd` and the GMASDK android version have not been changed since v0.11.0.
> 
> @zenkog What version are you using in your live app? Could you share your build.gradle?

**Comment by zenkog** [comment]
And just in case, this is the `android/build.gradle`
<details>
<summary>android/build.gradle</summary>
```
buildscript {
    ext.kotlin_version = '1.4.21'
    repositories {
        google()  // Google's Maven repository
        jcenter()
        maven {
            url "http://download.flutter.io"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.5'
    }
}

allprojects {
    repositories {
        google()  // Google's Maven repository
        jcenter()
        maven {
            url "http://download.flutter.io"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
</details>

**Comment by zenkog** [comment]
Hi anything, anyone?

**Comment by qwea363636** [comment]
Facing the exact same issue here, so does interstitial Ad

```
E/AndroidRuntime(12993): FATAL EXCEPTION: main
E/AndroidRuntime(12993): Process: com.example.app, PID: 12993
E/AndroidRuntime(12993): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
E/AndroidRuntime(12993): 	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:70)
E/AndroidRuntime(12993): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:299)
E/AndroidRuntime(12993): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(12993): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(12993): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(12993): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(12993): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(12993): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime(12993): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(12993): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12993): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(12993): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(12993): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.InterstitialAd" on path: DexPathList[[zip file "/data/app/~~Cvpzcni1oeTgr4kv-Hy9zA==/com.example.app-Xwpn44UJkc0C0LGy2Li-OQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Cvpzcni1oeTgr4kv-Hy9zA==/com.example.app-Xwpn44UJkc0C0LGy2Li-OQ==/lib/x86, /data/app/~~Cvpzcni1oeTgr4kv-Hy9zA==/com.example.app-Xwpn44UJkc0C0LGy2Li-OQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(12993): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(12993): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(12993): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(12993): 	... 12 more
I/Process (12993): Sending signal. PID: 12993 SIG: 9
```

**Comment by jjliu15** [comment]
@zenkog can you try changing `com.google.android.gms:play-services-ads:19.8.0` to `com.google.android.gms:play-services-ads:19.7.0` in your app/build.gradle?

**Comment by Klein-Kodes** [comment]
> Facing the exact same issue here, so does interstitial Ad
> 
> ```
> E/AndroidRuntime(12993): FATAL EXCEPTION: main
> E/AndroidRuntime(12993): Process: com.example.app, PID: 12993
> E/AndroidRuntime(12993): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
> E/AndroidRuntime(12993): 	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:70)
> E/AndroidRuntime(12993): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:299)
> E/AndroidRuntime(12993): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/AndroidRuntime(12993): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/AndroidRuntime(12993): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> E/AndroidRuntime(12993): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/AndroidRuntime(12993): 	at android.os.MessageQueue.next(MessageQueue.java:335)
> E/AndroidRuntime(12993): 	at android.os.Looper.loop(Looper.java:183)
> E/AndroidRuntime(12993): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
> E/AndroidRuntime(12993): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(12993): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> E/AndroidRuntime(12993): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> E/AndroidRuntime(12993): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.InterstitialAd" on path: DexPathList[[zip file "/data/app/~~Cvpzcni1oeTgr4kv-Hy9zA==/com.example.app-Xwpn44UJkc0C0LGy2Li-OQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Cvpzcni1oeTgr4kv-Hy9zA==/com.example.app-Xwpn44UJkc0C0LGy2Li-OQ==/lib/x86, /data/app/~~Cvpzcni1oeTgr4kv-Hy9zA==/com.example.app-Xwpn44UJkc0C0LGy2Li-OQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
> E/AndroidRuntime(12993): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
> E/AndroidRuntime(12993): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> E/AndroidRuntime(12993): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> E/AndroidRuntime(12993): 	... 12 more
> I/Process (12993): Sending signal. PID: 12993 SIG: 9
> ```

Facing exact same issue with the same logs.

**Comment by zenkog** [comment]
> @zenkog can you try changing `com.google.android.gms:play-services-ads:19.8.0` to `com.google.android.gms:play-services-ads:19.7.0` in your app/build.gradle?

Hi Sorry I was busy with other things. 
I tried your suggestion and now it works. 

So I hope you can update your code to be able to handle the latest version as soon as possible. Now it is `20.1.0`

Thanks

**Comment by zenkog** [comment]
So For now the workaround is by downgrading to:
`com.google.android.gms:play-services-ads:19.7.0`
in `app/build.gradle`.

I will close this issue for now and if someone else still facing issue we can re-open it
Thanks

> @zenkog can you try changing `com.google.android.gms:play-services-ads:19.8.0` to `com.google.android.gms:play-services-ads:19.7.0` in your app/build.gradle?
