### ISSUE TITLE
App Crashes by watching Interstitials or Rewarded

### ISSUE THREAD

**Issue by adriancsbna** [googleads/googleads-mobile-flutter#228]
Hello everyone.

For a few days now I have been getting errors when I try to display Interstitial or Rewarded Ads. The App closes immediately when .load() is executed.
A few days ago it was working perfectly, and then suddenly it stopped working.

I am currently using Flutter 2.0.6, I have tried to downgrade it to 2.0.4 and .5
The plugin is in version ^0.12.1, I also tried upgrading and downgrading it.

I also found on StackOverflow a person who has the same problem: https://stackoverflow.com/questions/67300815/flutter-fatal-exception-error-when-loading-rewardedads-java-lang-instantiatione

Do you know what might be happening?

FATAL EXCEPTION: main
Process: com.--------.-------, PID: 6982
java.lang.InstantiationError: com.google.android.gms.ads.rewarded.RewardedAd
	at io.flutter.plugins.googlemobileads.FlutterRewardedAd.createRewardedAd(FlutterRewardedAd.java:154)
	at io.flutter.plugins.googlemobileads.FlutterRewardedAd.load(FlutterRewardedAd.java:95)
	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:330)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7755)

E/AndroidRuntime( 6982): 	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

---------------------------------------------------------------------------------------------

FATAL EXCEPTION: main
Process: com.------.------, PID: 7536
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:70)
	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:299)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.InterstitialAd" on path: DexPathList[[zip file "/data/app/~~ROv5zflD8r6-ekUZ6wJmAg==/com.-------.-------pt860CIZwWCbwFVWIezZeA==/base.apk"],nativeLibraryDirectories=[/data/app/~~ROv5zflD8r6-ekUZ6wJmAg==/com.-----.-------pt860CIZwWCbwFVWIezZeA==/lib/arm64, /data/app/~~ROv5zflD8r6-ekUZ6wJmAg==/com.-----.-------pt860CIZwWCbwFVWIezZeA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /product/lib64]]

**Comment by jjliu15** [comment]
Can you check the version of GMASDK specified in your `build.gradle`? 
The plugin is currently only at 19.7.0, although we are working on upgrading to the latest version - which updated the class paths of Interstitial and Rewarded Ads.

**Comment by adriancsbna** [comment]
Hello @jjliu15 

I don't have any version of GMASDK set in build.gradle. It is not specified in the plugin documentation.
Which one should I write?

**Comment by jjliu15** [comment]
Can you see if the guidance in this other issue solves the issue? https://github.com/googleads/googleads-mobile-flutter/issues/199

**Comment by adriancsbna** [comment]
Hi @jjliu15 
I have added it and it still fails. I did a flutter clean but it didn't work either.

**Comment by adriancsbna** [comment]
Hi @jjliu15
I forgot to mention, that I also use two mediation groups, maybe it has something to do with it. I use AppLovin and Facebook and for this I add in dependences the following:
    implementation 'com.google.ads.mediation:applovin:10.1.2.0'.
    implementation 'com.google.ads.mediation:facebook:6.4.0.0'.

**Comment by adriancsbna** [comment]
HI @jjliu15

I managed to solve the problem by changing the version of the mediations to an older version.
I guess they were using a more current version of the SDK than the plugin and that's why it was crashing.

Thank you very much for everything.

The versions that I have put now are:
    implementation 'com.google.ads.mediation:applovin:9.15.2.0'.
    implementation 'com.google.ads.mediation:facebook:6.3.0.1'.
