### ISSUE TITLE
issues with smartBanner and InterstitialAd with google ads

### ISSUE THREAD

**Issue by hussam132** [googleads/googleads-mobile-flutter#232]
I'm facing two issue with google_mobile_ads 
the flutter doctor commend result:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.3) 
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.56.2)
[√] Connected device (4 available)

• No issues found!
```
 
1)  first with the banner and smart banner size and adaptive size:-

a)   I cannot use the adaptive banner size the code did not give any suggestions about it also I'm getting error when I use it like this  `AdSize.getAnchoredAdaptiveBannerAdSize(Orientation, int)` getting this error` The method 'getAnchoredAdaptiveBannerAdSize' isn't defined for the type 'AdSize'.`

b)    my banner works fine with every size but when I changed to  `AdSize.smartBanner`  I'm getting this error

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Container(Alignment.center, bg: Color(0x00000000), constraints: BoxConstraints(w=-1.0, h=-1.0; NOT NORMALIZED), dirty):
BoxConstraints has both a negative minimum width and a negative minimum height.

The offending constraints were: BoxConstraints(w=-1.0, h=-1.0; NOT NORMALIZED)
The relevant error-causing widget was
Container
lib\components\banner_ads.dart:65
When the exception was thrown, this was the stack
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError
package:flutter/…/rendering/box.dart:517
#1      BoxConstraints.debugAssertIsValid.<anonymous closure>
package:flutter/…/rendering/box.dart:544
#2      BoxConstraints.debugAssertIsValid
package:flutter/…/rendering/box.dart:565
#3      new ConstrainedBox
package:flutter/…/widgets/basic.dart:2293
#4      Container.build
package:flutter/…/widgets/container.dart:428
```

and this's my banner code 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:img2pdf/services/ad_manager.dart';
import 'package:provider/provider.dart';

class BannerAdContainer extends StatefulWidget {
  final size;

  const BannerAdContainer({Key? key,@required this.size}) : super(key: key);
  @override
  _BannerAdContainerState createState() => _BannerAdContainerState();
}

class _BannerAdContainerState extends State<BannerAdContainer> {
  late BannerAd bannerAd;
  bool _isAdLoaded = false;

  @override
  void dispose() {
    bannerAd.dispose();
    super.dispose();
  }

  @override
  Future<void> didChangeDependencies() async {
    super.didChangeDependencies();
    final adHelper = Provider.of<AdHelper>(context, listen: false);
    adHelper.initialization.then((status) {
      setState(() {
        bannerAd = BannerAd(
          adUnitId: AdHelper.bannerAdUnitId,
          size:widget.size, // AdSize.banner,
          request: AdRequest(),
          listener: AdListener(
            onAdLoaded: (_) {
              setState(() {
                _isAdLoaded = true;
              });
            },
            onAdFailedToLoad: (ad, error) {
              // Releases an ad resource when it fails to load
              //ad.dispose();

              print(
                  'Ad load failed (code=${error.code} message=${error.message})');
            },
          ),
        )..load();
      });
    });
  }

  Future<AdWidget> _setAdWidget() async {
    return AdWidget(ad: bannerAd);
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<AdWidget>(
        future: _setAdWidget(),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return Container(
              color: Colors.transparent,
              child: snapshot.data,
              width: bannerAd.size.width.toDouble(),
              height: bannerAd.size.height.toDouble(),
              alignment: Alignment.center,
            );
          } else {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
        });
  }
}
```

2)  the second issue is with `InterstitialAd` I just follow this [instructions ](https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter#7) but I'm facing this error after the error my app stop immediately 

```
Launching lib\main.dart on SM A515F in debug mode...
lib\main.dart:1
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54427/jJSuaD5mgoE=/ws
2
I/example.img2pd(15094): The ClassLoaderContext is a special shared library.
I/DynamiteModule(15094): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
I/DynamiteModule(15094): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
D/DynamitePackage(15094): Instantiated singleton DynamitePackage.
D/DynamitePackage(15094): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
I/Ads     (15094): Updating ad debug logging enablement.
I/WebViewFactory(15094): Loading com.google.android.webview version 87.0.4280.141 (code 428014133)
W/example.img2pd(15094): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/example.img2pd(15094): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/example.img2pd(15094): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/example.img2pd(15094): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/example.img2pd(15094): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_LibraryLoader(15094): Loaded native library version number "87.0.4280.141"
I/cr_CachingUmaRecorder(15094): Flushed 5 samples from 5 histograms.
W/example.img2pd(15094): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(15094): Requires BLUETOOTH permission
W/Ads     (15094): Update ad debug logging enablement as false
E/AndroidRuntime(15094): FATAL EXCEPTION: main
E/AndroidRuntime(15094): Process: com.example.myApp, PID: 15094
E/AndroidRuntime(15094): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/InterstitialAd;
E/AndroidRuntime(15094): 	at io.flutter.plugins.googlemobileads.FlutterInterstitialAd.load(FlutterInterstitialAd.java:70)
E/AndroidRuntime(15094): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:299)
E/AndroidRuntime(15094): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(15094): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(15094): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(15094): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(15094): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(15094): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(15094): 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/AndroidRuntime(15094): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15094): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(15094): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
E/AndroidRuntime(15094): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.InterstitialAd" on path: DexPathList[[zip file "/data/app/~~YRuLG5NbSJMz4bGmL8S4_A==/com.example.myApp-xPU3djqfAD1iGVNaM-gNqQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~YRuLG5NbSJMz4bGmL8S4_A==/com.example.myApp-xPU3djqfAD1iGVNaM-gNqQ==/lib/arm64, /data/app/~~YRuLG5NbSJMz4bGmL8S4_A==/com.example.myApp-xPU3djqfAD1iGVNaM-gNqQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(15094): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(15094): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(15094): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15094): 	... 12 more
I/Process (15094): Sending signal. PID: 15094 SIG: 9
Lost connection to device.
Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
Exited (sigterm)
```

and the code that I used to initialize , load and show the ads  in the main screen on the app
this `initState `method is in the first screen of my app 

```dart
 @override
  void initState() {
    // TODO: Initialize _interstitialAd
    _interstitialAd = InterstitialAd(
      adUnitId: AdHelper.interstitialAdUnitId,
      request: AdRequest(),
      listener: AdListener(
        onAdLoaded: (_) {
          _isInterstitialAdReady = true;
        },
        onAdFailedToLoad: (ad, err) {
          print('Failed to load an interstitial ad: ${err.message}');
          _isInterstitialAdReady = false;
          ad.dispose();
        },
        onAdClosed: (_) {
          // _moveToHome();
        },
      ),
    );
    _interstitialAd.load();
  }

  

 @override
  void dispose() {
    _interstitialAd.dispose();

    super.dispose();
  }

```

and I want to show the ads when I press button like this 

```dart
if (_isInterstitialAdReady) {
        _interstitialAd.show();
   } else { }
```

I will be glad to any more details if any is needed

**Comment by rednikisfun** [comment]
I have the same problem with Interstitial Ad. I want to show the InterstitialAd when the button is pressed, but when the ad is being loaded, the app crashes and exits

**Comment by jjliu15** [comment]
@hussam132 for your second issue, can you share your `build.gradle` files? Also maybe try updating your gradle version?

**Comment by hussam132** [comment]
@jjliu15 after updating the plugin to last version the second issue was resolved but the first one still exists

**Comment by jjliu15** [comment]
@hussam132 can you try using adaptive banners instead of smart banner? You can see the [example test app](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/example/lib/main.dart#L155-L187) for a reference.

Smart banners are currently deprecated in GMASDK, and will likely be deleted in a future release. Thus for the flutter plugin we will probably not be prioritizing smart banner.
