### ISSUE TITLE
Crashing with No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads

### ISSUE THREAD

**Issue by archanpaul** [googleads/googleads-mobile-flutter#249]
## Plugin Version
google_mobile_ads: ^0.13.0

## Steps to Reproduce

Added following in my app and app crashes.

```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(MyApp());
}
```

**Expected results:** App crashes.

**Actual results:** App should run.

<details>
  <summary>Logs</summary>

```
E/flutter (20335): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)
E/flutter (20335): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (20335): <asynchronous suspension>
E/flutter (20335):
E/flutter (20335): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)
E/flutter (20335): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (20335): <asynchronous suspension>
E/flutter (20335): #1      MobileAds.initialize
package:google_mobile_ads/src/mobile_ads.dart:49
                                                ^
1 warning
E/flutter (20335): <asynchronous suspension>
E/flutter (20335):
E/AndroidRuntime(20335): FATAL EXCEPTION: main
E/AndroidRuntime(20335): Process: XXXX, PID: 20335
E/AndroidRuntime(20335): java.lang.NoSuchMethodError: No static method initialize(Landroid/content/Context;Ljava/lang/String;)V in class Lcom/google/android/gms/ads/MobileAds; or its super classes (declaration of 'com.google.android.gms.ads.MobileAds' appears in /data/app/XXXX-BbXNBwX0a8tiP_9KPCTZBQ==/base.apk)
E/AndroidRuntime(20335): 	at io.flutter.plugins.firebaseadmob.FirebaseAdMobPlugin.callInitialize(FirebaseAdMobPlugin.java:219)
E/AndroidRuntime(20335): 	at io.flutter.plugins.firebaseadmob.FirebaseAdMobPlugin.onMethodCall(FirebaseAdMobPlugin.java:471)
E/AndroidRuntime(20335): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(20335): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(20335): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(20335): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(20335): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(20335): 	at android.os.Looper.loop(Looper.java:197)
E/AndroidRuntime(20335): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(20335): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20335): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(20335): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process (20335): Sending signal. PID: 20335 SIG: 9
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_IN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

```
</details>

**Comment by blasten** [comment]
The error is:

```
E/AndroidRuntime(20335): FATAL EXCEPTION: main
E/AndroidRuntime(20335): Process: XXXX, PID: 20335
E/AndroidRuntime(20335): java.lang.NoSuchMethodError: No static method initialize(Landroid/content/Context;Ljava/lang/String;)V in class Lcom/google/android/gms/ads/MobileAds; or its super classes (declaration of 'com.google.android.gms.ads.MobileAds' appears in /data/app/XXXX-BbXNBwX0a8tiP_9KPCTZBQ==/base.apk)
E/AndroidRuntime(20335): 	at io.flutter.plugins.firebaseadmob.FirebaseAdMobPlugin.callInitialize(FirebaseAdMobPlugin.java:219)
E/AndroidRuntime(20335): 	at io.flutter.plugins.firebaseadmob.FirebaseAdMobPlugin.onMethodCall(FirebaseAdMobPlugin.java:471)
E/AndroidRuntime(20335): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(20335): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(20335): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(20335): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(20335): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(20335): 	at android.os.Looper.loop(Looper.java:197)
E/AndroidRuntime(20335): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(20335): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20335): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(20335): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process (20335): Sending signal. PID: 20335 SIG: 9
```

Does this have to do with the recent bump of the GMS SDK, @jjliu15 ?

**Comment by blasten** [comment]
Actually, @archanpaul you are using a deprecated version of the admob plugin.

Please update the plugin dependency in pubspec.yaml:
```
google_mobile_ads: ^0.13.0
```
