### ISSUE TITLE
Many MissingPluginExceptions

### ISSUE THREAD

**Issue by amicharski** [googleads/googleads-mobile-flutter#287]
## Steps to Reproduce

1. Use google_mobile_ads 0.13.0 on your project.
2. Use either audioplayers 0.18.0 or 0.19.0 on your project.
3. Have a banner ad in your project.
4. Use the audio player for something in your project.

**Expected results:** 
The audio player working.

**Actual results:** 
Audio player doesn't work and a lot of MissingPluginExceptions.

<details>
  <summary>Logs</summary>

```
I can't fit all of this in here so I uploaded it here: http://elvis.rowan.edu/~michar52/misc/githublogs
```

```
   info - Name non-constant identifiers using lowerCamelCase - lib\controller.dart:85:14 - non_constant_identifier_names
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead -
          lib\controller.dart:93:26 - deprecated_member_use
   info - This function has a return type of 'Obstacle', but doesn't end with a return statement - lib\controller.dart:124:12 -
          missing_return
   info - Unused import: 'package:vector_math/vector_math_64.dart' - lib\full_drag.dart:6:8 - unused_import
   info - Unused import: 'package:audioplayers/audioplayers.dart' - lib\main.dart:4:8 - unused_import
   info - The declaration '_INTRO' isn't referenced - lib\main.dart:13:7 - unused_element
   info - The declaration '_initGoogleMobileAds' isn't referenced - lib\main.dart:25:32 - unused_element
   info - Unused import: 'dart:io' - lib\model.dart:7:8 - unused_import
   info - Unused import: 'package:path/path.dart' - lib\model.dart:9:8 - unused_import
   info - 'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead -
          lib\model.dart:40:17 - deprecated_member_use
   info - Unused import: 'package:audioplayers/audioplayers.dart' - lib\view.dart:3:8 - unused_import
   info - The member 'notifyListeners' can only be used within 'package:flutter/src/foundation/change_notifier.dart' or a test -
          lib\view.dart:259:32 - invalid_use_of_visible_for_testing_member
   info - The member 'notifyListeners' can only be used within instance members of subclasses of
          'package:flutter/src/foundation/change_notifier.dart' - lib\view.dart:259:32 - invalid_use_of_protected_member
   info - The value of the local variable 'centerX' isn't used - lib\view.dart:493:12 - unused_local_variable
   info - The value of the local variable 'blue' isn't used - lib\view.dart:498:11 - unused_local_variable
```

```
A:\AndroidProjects\d_ball>flutter doctor -v
[√] Flutter (Channel dev, 2.3.0-16.0.pre, on Microsoft Windows [Version 10.0.18363.1621], locale en-US)
    • Flutter version 2.3.0-16.0.pre at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa5883b78e (5 weeks ago), 2021-05-21 13:04:03 -0700
    • Engine revision 2f067fc4c5
    • Dart version 2.14.0 (build 2.14.0-136.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at A:\Android
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = A:\Android\platform-tools
    • Java binary at: A:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2.0)
    • Android Studio at A:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at A:\ProgramFiles\IntelliJ IDEA Community Edition 2020.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
```

</details>

**Comment by amicharski** [comment]
This is everything when I try to run it.

Running Gradle task 'assembleDebug'...
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:13: warning: [deprecation] UnifiedNativeAd in com.google.android.gms.ads.formats has been deprecated
import com.google.android.gms.ads.formats.UnifiedNativeAd;
                                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:14: warning: [deprecation] UnifiedNativeAdView in com.google.android.gms.ads.formats has been deprecated
import com.google.android.gms.ads.formats.UnifiedNativeAdView;
                                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:25: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:10: warning: [deprecation] RewardItem in com.google.android.gms.ads.reward has been deprecated
import com.google.android.gms.ads.reward.RewardItem;
                                        ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:11: warning: [deprecation] RewardedVideoAd in com.google.android.gms.ads.reward has been deprecated
import com.google.android.gms.ads.reward.RewardedVideoAd;
                                        ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:12: warning: [deprecation] RewardedVideoAdListener in com.google.android.gms.ads.reward has been deprecated
import com.google.android.gms.ads.reward.RewardedVideoAdListener;
                                        ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:18: warning: [deprecation] InterstitialAd in com.google.android.gms.ads has been deprecated
import com.google.android.gms.ads.InterstitialAd;
                                 ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:19: warning: [deprecation] NativeAdOptions in com.google.android.gms.ads.formats has been deprecated
import com.google.android.gms.ads.formats.NativeAdOptions;
                                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:20: warning: [deprecation] UnifiedNativeAd in com.google.android.gms.ads.formats has been deprecated
import com.google.android.gms.ads.formats.UnifiedNativeAd;
                                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:21: warning: [deprecation] UnifiedNativeAdView in com.google.android.gms.ads.formats has been deprecated
import com.google.android.gms.ads.formats.UnifiedNativeAdView;
                                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java:74: warning: [deprecation] addTestDevice(String) in Builder has been deprecated
        if (device != null) builder.addTestDevice(device);
                                   ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java:93: warning: [deprecation] setBirthday(Date) in Builder has been deprecated
      else builder.setBirthday(new Date((Long) birthday));
                  ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java:102: warning: [deprecation] setGender(int) in Builder has been deprecated
          builder.setGender(gender);
                 ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java:111: warning: [deprecation] setIsDesignedForFamilies(boolean) in Builder has been deprecated
    if (designedForFamilies != null) builder.setIsDesignedForFamilies(designedForFamilies);
                                            ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java:115: warning: [deprecation] tagForChildDirectedTreatment(boolean) in Builder has been deprecated
    if (childDirected != null) builder.tagForChildDirectedTreatment(childDirected);
                                      ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:67: warning: [deprecation] UnifiedNativeAdView in com.google.android.gms.ads.formats has been deprecated
    UnifiedNativeAdView createNativeAd(UnifiedNativeAd nativeAd, Map<String, Object> customOptions);
    ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:67: warning: [deprecation] UnifiedNativeAd in com.google.android.gms.ads.formats has been deprecated
    UnifiedNativeAdView createNativeAd(UnifiedNativeAd nativeAd, Map<String, Object> customOptions);
                                       ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:80: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(Registrar registrar) {
                                  ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:106: warning: [deprecation] <T>valuePublishedByPlugin(String) in PluginRegistry has been deprecated
    final FirebaseAdMobPlugin adMobPlugin = registry.valuePublishedByPlugin(GENERATED_PLUGIN_KEY);
                                                    ^
  where T is a type-variable:
    T extends Object declared in method <T>valuePublishedByPlugin(String)
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:156: warning: [deprecation] <T>valuePublishedByPlugin(String) in PluginRegistry has been deprecated
    final FirebaseAdMobPlugin adMobPlugin = registry.valuePublishedByPlugin(GENERATED_PLUGIN_KEY);
                                                    ^
  where T is a type-variable:
    T extends Object declared in method <T>valuePublishedByPlugin(String)
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\FirebaseAdMobPlugin.java:217: warning: [deprecation] initialize(Context,String) in MobileAds has been deprecated
    MobileAds.initialize(applicationContext, appId);
             ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:17: warning: [deprecation] RewardedVideoAdListener in com.google.android.gms.ads.reward has been deprecated
public class RewardedVideoAdWrapper implements RewardedVideoAdListener {
                                               ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:20: warning: [deprecation] RewardedVideoAd in com.google.android.gms.ads.reward has been deprecated
  private final RewardedVideoAd rewardedInstance;
                ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:52: warning: [deprecation] RewardItem in com.google.android.gms.ads.reward has been deprecated
  public void onRewarded(RewardItem rewardItem) {
                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\RewardedVideoAdWrapper.java:80: warning: [deprecation] getRewardedVideoAdInstance(Context) in MobileAds has been deprecated
    this.rewardedInstance = MobileAds.getRewardedVideoAdInstance(activity);
                                     ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:119: warning: [deprecation] onAdFailedToLoad(int) in AdListener has been deprecated
  public void onAdFailedToLoad(int errorCode) {
              ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:141: warning: [deprecation] onAdLeftApplication() in AdListener has been deprecated
  public void onAdLeftApplication() {
              ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:238: warning: [deprecation] InterstitialAd in com.google.android.gms.ads has been deprecated
    private InterstitialAd interstitial = null;
            ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:248: warning: [deprecation] InterstitialAd in com.google.android.gms.ads has been deprecated
      interstitial = new InterstitialAd(activity);
                         ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:271: warning: [deprecation] UnifiedNativeAdView in com.google.android.gms.ads.formats has been deprecated
    private UnifiedNativeAdView adView;
            ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:298: warning: [deprecation] NativeAdOptions in com.google.android.gms.ads.formats has been deprecated
              .withNativeAdOptions(new NativeAdOptions.Builder().build())
                                       ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:291: warning: [deprecation] UnifiedNativeAd in com.google.android.gms.ads.formats has been deprecated
                  new UnifiedNativeAd.OnUnifiedNativeAdLoadedListener() {
                      ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:291: warning: [deprecation] OnUnifiedNativeAdLoadedListener in UnifiedNativeAd has been deprecated
                  new UnifiedNativeAd.OnUnifiedNativeAdLoadedListener() {
                                     ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:293: warning: [deprecation] UnifiedNativeAd in com.google.android.gms.ads.formats has been deprecated
                    public void onUnifiedNativeAdLoaded(UnifiedNativeAd unifiedNativeAd) {
                                                        ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:290: warning: [deprecation] forUnifiedNativeAd(OnUnifiedNativeAdLoadedListener) in Builder has been deprecated
              .forUnifiedNativeAd(
              ^
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_admob-0.11.2\android\src\main\java\io\flutter\plugins\firebaseadmob\MobileAd.java:298: warning: [deprecation] withNativeAdOptions(NativeAdOptions) in Builder has been deprecated
              .withNativeAdOptions(new NativeAdOptions.Builder().build())
              ^
36 warnings
C:\Users\16094\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_mobile_ads-0.13.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdSize.java:70: warning: [deprecation] SMART_BANNER in AdSize has been deprecated
      super(AdSize.SMART_BANNER);
                  ^
1 warning

√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:51399/Ybm6nJBz57o=/ws
Syncing files to device sdk gphone x86 arm...
E/AudioAttributes( 7921): Invalid stream type -2147483648 for AudioAttributes
W/SoundPool::StreamManager( 7921): StreamMap: requested 100 streams, clamping to 32
E/flutter ( 7921): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method loadBannerAd on channel plugins.flutter.io/google_mobile_ads)
E/flutter ( 7921): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): #1      BannerAd.load (package:google_mobile_ads/src/ad_containers.dart:534:5)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): 
I/flutter ( 7921): RESULT: 1
E/flutter ( 7921): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 7921): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:78:24)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): #2      AudioCache.fetchToMemory (package:audioplayers/src/audio_cache.dart:92:27)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): #3      AudioCache.load (package:audioplayers/src/audio_cache.dart:115:31)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): #4      AudioCache.play (package:audioplayers/src/audio_cache.dart:159:17)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921): #5      AudioController.playLoop (package:d_ball/audio_controller.dart:28:18)
E/flutter ( 7921): <asynchronous suspension>
E/flutter ( 7921):

**Comment by amicharski** [comment]
This is the important part of my pubspec:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  audioplayers: 0.19.0 #downgrade from 0.19.0
  google_mobile_ads: 0.13.0 #downgrade from 0.13.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.6.2
  provider: ^5.0.0
  gestures: ^0.0.1
  path_provider: ^2.0.2
  confetti: ^0.5.4+1
  firebase_admob: ^0.11.0+1

**Comment by amicharski** [comment]
I fixed this issue by moving all of my dependencies out of `dev_dependencies` and into `dependencies` and upgrading path to 1.8.0 and taking off the carrot `^` from everything.
