### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by fokhwar** [googleads/googleads-mobile-flutter#299]
## Plugin Version

google_mobile_ads: ^0.13.2
Flutter 2.3.0-17.0
Dart 2.14.0

## Steps to Reproduce

1. paste google mobile ads in pubspec.yaml and run 'flutter pub get'.
2. paste this line in flutter's main function. 
`MobileAds.instance.initialize();`
3. After run, will see below error.
`Null check operator used on a null value`

**Expected results:** 
App should be run.

**Actual results:** 
Error: **Null check operator used on a null value**
<details>
  <summary>Logs</summary>

`[VERBOSE-2:ui_dart_state.cc(213)] Unhandled Exception: Null check operator used on a null value
           #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:121:86)
           #1      MethodChannel.setMethodCallHandler (package:flutter/src/services/platform_channel.dart:375:5)
           #2      new AdInstanceManager (package:google_mobile_ads/src/ad_instance_manager.dart:44:13)
           #3      instanceManager (package:google_mobile_ads/src/ad_instance_manager.dart:32:37)
           #4      instanceManager (package:google_mobile_ads/src/ad_instance_manager.dart)
           #5      MobileAds._init (package:google_mobile_ads/src/mobile_ads.dart:77:5)
           #6      MobileAds._instance (package:google_mobile_ads/src/mobile_ads.dart:36:53)
           #7      MobileAds._instance (package:google_mobile_ads/src/mobile_ads.dart)
           #8      MobileAds.instance (package:google_mobile_ads/src/mobile_ads.dart:39:36)
           #9      main (package:helloads/main.dart:7:13)
           #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
           #11  <…>
`
</details>

**Comment by fokhwar** [comment]
Documentation make me assume it requires only 'MobileAds.instance.initialize()'. 
I did not include the 'ensureInitialized()' function. Adding that function solved my error. 
Thanks

`WidgetsFlutterBinding.ensureInitialized();`
`MobileAds.instance.initialize();`
