### ISSUE TITLE
Unable to use `google_mobile_ads` with other firebase dependencies

### ISSUE THREAD

**Issue by ggirotto** [googleads/googleads-mobile-flutter#374]
## Plugin Version

`0.13.4`

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `pubspec.yaml` with the following dependencies:

```
firebase_core: ^1.6.0
  cloud_firestore: ^2.5.2
  cloud_functions: ^3.0.3
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^8.3.2
  firebase_remote_config: ^0.11.0
  firebase_messaging: ^10.0.7
  google_mobile_ads: ^0.13.4
```

3. Replace `ios/Podfile` with the following:

<details>
<summary>Podfile</summary>

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.6.0'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

</details>

4. Try to run the project

**Actual results:**

It hands with `Waiting for observatory port to be available...` or sometimes crash in startup with the error:

```
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:60007/6XKEKen_s-8=/
[   +4 ms] "flutter run" took 42,588ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

<details>
  <summary>Logs</summary>

[logs.txt](https://github.com/googleads/googleads-mobile-flutter/files/7154289/logs.txt)

```
```

Analyzing bug...                                                        
No issues found! (ran in 3.3s)

```
```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en-BR)
    • Flutter version 2.2.3 at /Users/guilhermegirotto/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/guilhermegirotto/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • 9022EA23-AC9A-419D-B12D-98ED4351E1A5 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64 • macOS 11.5.2 20G95 darwin-x64
    ! Error: Girotto iPhone is busy: Copying cache files from device. Xcode will continue when Girotto iPhone is finished. (code -10)

• No issues found!

```
```

</details>

**Comment by ggirotto** [comment]
For those facing a similar issue, try to run the project in a physical device. There the output error message is much clearer and it was indicating a problem in my `Info.plist` file.
