### ISSUE TITLE
The Google Mobile Ads SDK was initialized incorrectly

### ISSUE THREAD

**Issue by erperejildo** [googleads/googleads-mobile-flutter#454]
Following this: https://developers.google.com/admob/flutter/quick-start

I have this:

- Flutter 1.22.0 or higher
- Android
- Android Studio 3.2 or higher
- Target Android API level 19 or higher
- Set compileSdkVersion to 28 or higher

This (with my ID):
```
<manifest>
    <application>
        <!-- Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
    <application>
<manifest>
```

And this:
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();

  runApp(MyApp());
}
```

Version: `google_mobile_ads: ^1.0.0`

flutter doctor:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (2 available)

• No issues found!
```

Error on new project:
```
Installing build/app/outputs/flutter-apk/app.apk...
E/AndroidRuntime(14894): FATAL EXCEPTION: main
E/AndroidRuntime(14894): Process: com.drodriguez.my_rents, PID: 14894
E/AndroidRuntime(14894): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
E/AndroidRuntime(14894): 
E/AndroidRuntime(14894): ******************************************************************************
E/AndroidRuntime(14894): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(14894): * should follow the instructions here:                                       *
E/AndroidRuntime(14894): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(14894): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(14894): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(14894): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(14894): ******************************************************************************
E/AndroidRuntime(14894): 
E/AndroidRuntime(14894): 
E/AndroidRuntime(14894): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
E/AndroidRuntime(14894): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
E/AndroidRuntime(14894): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
E/AndroidRuntime(14894): 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
E/AndroidRuntime(14894): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
E/AndroidRuntime(14894): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14894): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(14894): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(14894): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14894): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(14894): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(14894): Caused by: java.lang.IllegalStateException: 
E/AndroidRuntime(14894): 
E/AndroidRuntime(14894): ******************************************************************************
E/AndroidRuntime(14894): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(14894): * should follow the instructions here:                                       *
E/AndroidRuntime(14894): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(14894): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(14894): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(14894): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(14894): ******************************************************************************
E/AndroidRuntime(14894): 
E/AndroidRuntime(14894): 
E/AndroidRuntime(14894): 	at com.google.android.gms.internal.ads.zzbhk.attachInfo(com.google.android.gms:play-services-ads-lite@@20.4.0:20)
E/AndroidRuntime(14894): 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@20.4.0:1)
E/AndroidRuntime(14894): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
E/AndroidRuntime(14894): 	... 10 more

```

**Comment by erperejildo** [comment]
Those errors point to this link:
https://developers.google.com/admob/android/quick-start#java

Do I need to modify something in my MainActivity?

**Comment by erperejildo** [comment]
I had this inside `<activity>`:
```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
```

**Comment by NiuXiaoGuang** [comment]
How did you finally solve the problem

**Comment by erperejildo** [comment]
moving that meta outside activity
