### ISSUE TITLE
App crashes with version 1.0.1 on device without GMS

### ISSUE THREAD

**Issue by ecorradini** [googleads/googleads-mobile-flutter#498]
## Plugin Version

1.0.1

## Steps to Reproduce
1. Compile release version of the app.
2. Run on a device without Google Play Services installed.

**Expected results:** 
App running correctly as in version 0.13.6

**Actual results:** 
App crashes.
<details>
  <summary>Logs</summary>

```
java.lang.LinkageError: Method java.lang.Object com.google.android.gms.internal.ads.dl3.j() overrides final method in class Lcom/google/android/gms/internal/ads/vk3; (declaration of 'com.google.android.gms.internal.ads.dl3' appears in base.apk!classes2.dex)
        at com.google.android.gms.internal.ads.sr0.zza(SourceFile:6)
        at com.google.android.gms.internal.ads.rf2.a(SourceFile:47)
        at com.google.android.gms.internal.ads.b42.t7(SourceFile:7)
        at com.google.android.gms.internal.ads.b42.r0(SourceFile:2)
        at com.google.android.gms.internal.ads.wu.j(SourceFile:28)
        at com.google.android.gms.ads.BaseAdView.b(SourceFile:1)
        at io.flutter.plugins.googlemobileads.FlutterBannerAd.load(SourceFile:6)
        at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(SourceFile:57)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:2)
        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(SourceFile:2)
        at io.flutter.embedding.engine.dart.DartMessenger.a(SourceFile:2)
        at io.flutter.embedding.engine.dart.DartMessenger.b(Unknown Source:0)
        at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

```
No issues found! (ran in 7.5s)
```

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Versione 10.0.22000.434], locale it-IT)
    • Flutter version 2.8.1 at E:\Devel\Software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\henry\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • ELS NX9 (mobile) • K5J0220310011877 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!
```

</details>

**Comment by ecorradini** [comment]
On devices without GMS add
```
-keep public class com.google.android.gms.** { public protected *; }
```
on `proguard-rules.pro`
