### ISSUE TITLE
Banner ad keep rebuilding the entire screen when it reloads in andriod

### ISSUE THREAD

**Issue by dudeismail** [googleads/googleads-mobile-flutter#508]
## Plugin Version

google_mobile_ads: ^1.0.1

## Description
I'm testing a banner ad in my home screen,but it rebuilding the home screen automatically every time it reloads the ad( for every one minute approxmetly).
I'm using firebase & streams to show products,videos etc inside a listview. At the end of the list I'm using a container to show banner ad.

Here is the video:
https://user-images.githubusercontent.com/52096030/152775540-23abf29f-dbc0-4c85-bf46-d199cea3e82f.mp4

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 18.04.6 LTS 4.15.0-163-generic,
    locale en_IN)
    • Flutter version 2.5.3 at /home/student/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/student/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at
      /home/student/mydev/android-studio-ide-193.6626763-linux/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • DUA AL00 (mobile) • SMQ9K18824439550 • android-arm64  • Android 8.1.0 (API
      27)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      97.0.4692.99

! Doctor found issues in 1 category.
```

Here is some code: 
```
BannerAd _bannerAd;
  bool _isBannerAdReady = false;

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
        size: AdSize.largeBanner,
        adUnitId: AdHelper.bannerAdUnitID,
        listener: BannerAdListener(
          onAdLoaded: (_){
            setState(() {
              _isBannerAdReady = true;
            });
          },
          onAdFailedToLoad: (ad,err){
            print("Error: ${err.message}");
            _isBannerAdReady = false;
            ad.dispose();
          }
        ),
        request: AdRequest()
    );
    _bannerAd.load();
  }

  @override
  void dispose() {
    super.dispose();
    _bannerAd.dispose();
  }
```

Ad WIdget (at end of the listview):
```
if(_isBannerAdReady)
            Column(
              children: [
                Container(
                  height: _bannerAd.size.height.toDouble(),
                  width: _bannerAd.size.width.toDouble(),
                  child: AdWidget(ad: _bannerAd,),
                ),
                SizedBox(height: 50.0,)
              ],
            )
```

<details>
  <summary>Logs</summary>
Flutter run --verbose : 

```
[ +206 ms] executing: uname -m
[ +103 ms] Exit code 0 from: uname -m
[   +1 ms] x86_64
[  +20 ms] executing: [/home/student/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[   +2 ms] executing: [/home/student/snap/flutter/common/flutter/] git tag
--points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +45 ms] Exit code 0 from: git tag --points-at
18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] 2.5.3
[  +30 ms] executing: [/home/student/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/student/snap/flutter/common/flutter/] git ls-remote
--get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +279 ms] executing: [/home/student/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +214 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +18 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +7 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +267 ms] executing: /home/student/Android/Sdk/platform-tools/adb devices -l
[ +181 ms] List of devices attached
[  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +323 ms] Skipping pub get: version match.
[ +101 ms] Found plugin cloud_firestore at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore-2.5.3/
[  +44 ms] Found plugin cloud_firestore_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore_web-2.4.2/
[  +36 ms] Found plugin firebase_auth at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth-3.1.1/
[  +12 ms] Found plugin firebase_auth_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth_web-3.1.0/
[   +7 ms] Found plugin firebase_core at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core-1.6.0/
[   +8 ms] Found plugin firebase_core_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core_web-1.1.0/
[   +8 ms] Found plugin firebase_storage at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage-10.0.3/
[  +11 ms] Found plugin firebase_storage_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage_web-3.0.2/
[   +6 ms] Found plugin flutter_inappwebview at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_inappwebview-5.3.2/
[  +13 ms] Found plugin flutter_plugin_android_lifecycle at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_plugin_android_lifecycle-2.0.5/
[   +6 ms] Found plugin google_mobile_ads at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/goo
gle_mobile_ads-1.0.1/
[  +32 ms] Found plugin image_picker at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker-0.8.4+4/
[  +10 ms] Found plugin image_picker_for_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_for_web-2.1.4/
[  +58 ms] Found plugin share at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/sha
re-2.0.4/
[  +43 ms] Found plugin url_launcher at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher-6.0.17/
[   +6 ms] Found plugin url_launcher_android at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_android-6.0.13/
[   +5 ms] Found plugin url_launcher_ios at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_ios-6.0.13/
[   +9 ms] Found plugin url_launcher_linux at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_linux-2.0.2/
[  +10 ms] Found plugin url_launcher_macos at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_macos-2.0.2/
[   +9 ms] Found plugin url_launcher_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_web-2.0.4/
[  +10 ms] Found plugin url_launcher_windows at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_windows-2.0.2/
[ +502 ms] Found plugin cloud_firestore at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore-2.5.3/
[  +15 ms] Found plugin cloud_firestore_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore_web-2.4.2/
[  +27 ms] Found plugin firebase_auth at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth-3.1.1/
[   +6 ms] Found plugin firebase_auth_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth_web-3.1.0/
[   +6 ms] Found plugin firebase_core at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core-1.6.0/
[   +5 ms] Found plugin firebase_core_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core_web-1.1.0/
[   +4 ms] Found plugin firebase_storage at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage-10.0.3/
[   +7 ms] Found plugin firebase_storage_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage_web-3.0.2/
[   +3 ms] Found plugin flutter_inappwebview at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_inappwebview-5.3.2/
[  +10 ms] Found plugin flutter_plugin_android_lifecycle at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_plugin_android_lifecycle-2.0.5/
[   +4 ms] Found plugin google_mobile_ads at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/goo
gle_mobile_ads-1.0.1/
[  +14 ms] Found plugin image_picker at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker-0.8.4+4/
[   +4 ms] Found plugin image_picker_for_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_for_web-2.1.4/
[  +41 ms] Found plugin share at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/sha
re-2.0.4/
[  +20 ms] Found plugin url_launcher at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher-6.0.17/
[   +4 ms] Found plugin url_launcher_android at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_android-6.0.13/
[   +4 ms] Found plugin url_launcher_ios at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_ios-6.0.13/
[   +2 ms] Found plugin url_launcher_linux at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_linux-2.0.2/
[   +3 ms] Found plugin url_launcher_macos at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_macos-2.0.2/
[   +7 ms] Found plugin url_launcher_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_web-2.0.4/
[   +3 ms] Found plugin url_launcher_windows at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_windows-2.0.2/
[ +279 ms] Generating
/home/student/fludev/factsforever/android/app/src/main/java/io/flutter/plugins/G
eneratedPluginRegistrant.java
[ +756 ms] Launching lib/main.dart on Chrome in debug mode...
[ +301 ms] Updating assets
[+1343 ms] Waiting for connection from debug service on Chrome...
[  +39 ms] Found plugin cloud_firestore at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore-2.5.3/
[   +4 ms] Found plugin cloud_firestore_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore_web-2.4.2/
[  +10 ms] Found plugin firebase_auth at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth-3.1.1/
[   +4 ms] Found plugin firebase_auth_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth_web-3.1.0/
[   +2 ms] Found plugin firebase_core at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core-1.6.0/
[   +3 ms] Found plugin firebase_core_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core_web-1.1.0/
[   +2 ms] Found plugin firebase_storage at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage-10.0.3/
[   +4 ms] Found plugin firebase_storage_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage_web-3.0.2/
[   +2 ms] Found plugin flutter_inappwebview at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_inappwebview-5.3.2/
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_plugin_android_lifecycle-2.0.5/
[   +2 ms] Found plugin google_mobile_ads at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/goo
gle_mobile_ads-1.0.1/
[   +6 ms] Found plugin image_picker at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker-0.8.4+4/
[   +2 ms] Found plugin image_picker_for_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_for_web-2.1.4/
[  +20 ms] Found plugin share at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/sha
re-2.0.4/
[  +12 ms] Found plugin url_launcher at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher-6.0.17/
[   +2 ms] Found plugin url_launcher_android at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_android-6.0.13/
[   +2 ms] Found plugin url_launcher_ios at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_ios-6.0.13/
[   +2 ms] Found plugin url_launcher_linux at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_linux-2.0.2/
[   +4 ms] Found plugin url_launcher_macos at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_macos-2.0.2/
[   +5 ms] Found plugin url_launcher_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_web-2.0.4/
[   +2 ms] Found plugin url_launcher_windows at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_windows-2.0.2/
[  +42 ms] Found plugin cloud_firestore at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore-2.5.3/
[   +4 ms] Found plugin cloud_firestore_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clo
ud_firestore_web-2.4.2/
[  +11 ms] Found plugin firebase_auth at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth-3.1.1/
[   +8 ms] Found plugin firebase_auth_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_auth_web-3.1.0/
[   +3 ms] Found plugin firebase_core at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core-1.6.0/
[   +5 ms] Found plugin firebase_core_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_core_web-1.1.0/
[   +3 ms] Found plugin firebase_storage at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage-10.0.3/
[   +4 ms] Found plugin firebase_storage_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fir
ebase_storage_web-3.0.2/
[   +2 ms] Found plugin flutter_inappwebview at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_inappwebview-5.3.2/
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flu
tter_plugin_android_lifecycle-2.0.5/
[   +5 ms] Found plugin google_mobile_ads at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/goo
gle_mobile_ads-1.0.1/
[   +7 ms] Found plugin image_picker at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker-0.8.4+4/
[   +2 ms] Found plugin image_picker_for_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/ima
ge_picker_for_web-2.1.4/
[  +21 ms] Found plugin share at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/sha
re-2.0.4/
[  +20 ms] Found plugin url_launcher at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher-6.0.17/
[   +4 ms] Found plugin url_launcher_android at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_android-6.0.13/
[   +5 ms] Found plugin url_launcher_ios at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_ios-6.0.13/
[   +6 ms] Found plugin url_launcher_linux at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_linux-2.0.2/
[   +2 ms] Found plugin url_launcher_macos at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_macos-2.0.2/
[   +4 ms] Found plugin url_launcher_web at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_web-2.0.4/
[   +3 ms] Found plugin url_launcher_windows at
/home/student/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url
_launcher_windows-2.0.2/
[ +517 ms] <- reset
[  +24 ms] /home/student/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/student/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/f
rontend_server.dart.snapshot --sdk-root
/home/student/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.MRINQN/flutter_tool.AFAAMM/app.dill --libraries-spec
file:///home/student/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libra
ries.json --packages
/home/student/fludev/factsforever/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
/tmp/flutter_tools.MRINQN/flutter_tools.RKWEHA --filesystem-scheme
org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///home/student/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kerne
l/flutter_ddc_sdk.dill --no-sound-null-safety
[  +26 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+75687 ms] Waiting for connection from debug service on Chrome... (completed in
76.6s)
[   +1 ms] Synced 32.9MB.
[   +6 ms] <- accept
[        ] Caching compiled dill
[ +226 ms] Using Google Chrome 97.0.4692.99 

[   +6 ms] executing: uname -m
[  +42 ms] Exit code 0 from: uname -m
[        ] x86_64
[+1239 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:33427/devtools/browser/ffd94917-3225-4d8c-a1ff-ebbcf67b5fbd
[+4045 ms] DwdsInjector: Received request for entrypoint at
http://localhost:36607/main_module.bootstrap.js
[  +44 ms] MetadataProvider: Loading debug metadata...
[  +39 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +21 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:36607/main_module.bootstrap.js
[+9798 ms] ChromeProxyService: Initializing expression compiler for
main_module.bootstrap.js with sound null safety: false
[ +173 ms] DevHandler: Debug service listening on
ws://127.0.0.1:37881/qlKCyWNlihM=/ws

[  +47 ms] This app is linked to the debug service:
ws://127.0.0.1:37881/qlKCyWNlihM=/ws
[  +27 ms] Debug service listening on ws://127.0.0.1:37881/qlKCyWNlihM=/ws
[        ] Running with unsound null safety
[        ] For more information see
https://dart.dev/null-safety/unsound-null-safety
[   +6 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".
[   +7 ms] An Observatory debugger and profiler on Chrome is available at:
           http://127.0.0.1:37881/qlKCyWNlihM=
[  +70 ms] TypeError: Cannot read properties of undefined (reading 'app')
               at Object.app$ [as app]

(http://localhost:36607/packages/firebase_core_web/src/interop/core.dart.lib
               .js:31:101)
               at new cloud_firestore_web.FirebaseFirestoreWeb.new

(http://localhost:36607/packages/cloud_firestore_web/src/write_batch_web.dar
               t.lib.js:934:64)
               at Function.registerWith

(http://localhost:36607/packages/cloud_firestore_web/src/write_batch_web.dar
               t.lib.js:834:73)
               at Object.registerPlugins

(http://localhost:36607/packages/factsforever/generated_plugin_registrant.da
               rt.lib.js:18:46)
               at main (http://localhost:36607/web_entrypoint.dart.lib.js:35:35)
               at main.next (<anonymous>)
               at runBody (http://localhost:36607/dart_sdk.js:40666:34)
               at Object._async [as async]
(http://localhost:36607/dart_sdk.js:40697:7)
               at main$
(http://localhost:36607/web_entrypoint.dart.lib.js:34:18)
               at http://localhost:36607/main_module.bootstrap.js:19:10
               at Array.forEach (<anonymous>)
               at window.$dartRunMain
               (http://localhost:36607/main_module.bootstrap.js:18:32)
               at <anonymous>:1:8
               at Object.runMain
               (http://localhost:36607/dwds/src/injected/client.js:8452:21)
               at http://localhost:36607/dwds/src/injected/client.js:24130:19
               at _wrapJsFunctionForAsync_closure.$protected
               (http://localhost:36607/dwds/src/injected/client.js:4461:15)
               at _wrapJsFunctionForAsync_closure.call$2
               (http://localhost:36607/dwds/src/injected/client.js:11511:12)
               at Object._asyncStartSync
               (http://localhost:36607/dwds/src/injected/client.js:4425:20)
               at main__closure3.$call$body$main__closure
               (http://localhost:36607/dwds/src/injected/client.js:24142:16)
               at main__closure3.call$1
               (http://localhost:36607/dwds/src/injected/client.js:24069:19)
               at StaticClosure._rootRunUnary
               (http://localhost:36607/dwds/src/injected/client.js:4823:18)
               at _CustomZone.runUnary$2$2
               (http://localhost:36607/dwds/src/injected/client.js:12879:39)
               at _CustomZone.runUnaryGuarded$1$2
               (http://localhost:36607/dwds/src/injected/client.js:12826:14)
               at _ForwardingStreamSubscription._sendData$1
               (http://localhost:36607/dwds/src/injected/client.js:12416:19)
               at _ForwardingStreamSubscription._add$1
               (http://localhost:36607/dwds/src/injected/client.js:12362:15)
               at _ForwardingStreamSubscription._add$1
               (http://localhost:36607/dwds/src/injected/client.js:12695:12)
               at _MapStream._handleData$2
               (http://localhost:36607/dwds/src/injected/client.js:12756:12)
               at _ForwardingStreamSubscription._handleData$1
               (http://localhost:36607/dwds/src/injected/client.js:12721:20)
               at BoundClosure.eval (eval at Closure_forwardCallTo
               (http://localhost:36607/dwds/src/injected/client.js:1701:14),
               <anonymous>:3:44)
               at StaticClosure._rootRunUnary
               (http://localhost:36607/dwds/src/injected/client.js:4823:18)
               at _CustomZone.runUnary$2$2
               (http://localhost:36607/dwds/src/injected/client.js:12879:39)
               at _CustomZone.runUnaryGuarded$1$2
               (http://localhost:36607/dwds/src/injected/client.js:12826:14)
               at _ControllerSubscription._sendData$1
               (http://localhost:36607/dwds/src/injected/client.js:12416:19)
               at _ControllerSubscription._add$1
               (http://localhost:36607/dwds/src/injected/client.js:12362:15)
               at _SyncStreamController._sendData$1
               (http://localhost:36607/dwds/src/injected/client.js:12201:32)
               at _SyncStreamController.add$1
               (http://localhost:36607/dwds/src/injected/client.js:12082:15)
               at BoundClosure.eval (eval at Closure_forwardInterceptedCallTo
               (http://localhost:36607/dwds/src/injected/client.js:1781:14),
               <anonymous>:3:45)
               at StaticClosure._rootRunUnary
               (http://localhost:36607/dwds/src/injected/client.js:4823:18)
               at _CustomZone.runUnary$2$2
               (http://localhost:36607/dwds/src/injected/client.js:12879:39)
               at _CustomZone.runUnaryGuarded$1$2
               (http://localhost:36607/dwds/src/injected/client.js:12826:14)
               at _ControllerSubscription._sendData$1
               (http://localhost:36607/dwds/src/injected/client.js:12416:19)
               at _ControllerSubscription._add$1
               (http://localhost:36607/dwds/src/injected/client.js:12362:15)
               at _SyncStreamController._sendData$1
               (http://localhost:36607/dwds/src/injected/client.js:12201:32)
               at _SyncStreamController.add$1
               (http://localhost:36607/dwds/src/injected/client.js:12082:15)
               at _GuaranteeSink.add$1
               (http://localhost:36607/dwds/src/injected/client.js:23581:25)
               at HtmlWebSocketChannel_closure1.call$1
               (http://localhost:36607/dwds/src/injected/client.js:23874:60)
               at _EventStreamSubscription_closure.call$1
               (http://localhost:36607/dwds/src/injected/client.js:18042:26)
               at StaticClosure._rootRunUnary
               (http://localhost:36607/dwds/src/injected/client.js:4829:16)
               at _CustomZone.runUnary$2$2
               (http://localhost:36607/dwds/src/injected/client.js:12879:39)
               at _CustomZone.runUnaryGuarded$1$2
               (http://localhost:36607/dwds/src/injected/client.js:12826:14)
               at _CustomZone_bindUnaryCallbackGuarded_closure.call$1
               (http://localhost:36607/dwds/src/injected/client.js:13016:25)
               at invokeClosure
               (http://localhost:36607/dwds/src/injected/client.js:1524:26)
               at WebSocket.<anonymous>
               (http://localhost:36607/dwds/src/injected/client.js:1543:18)
[+1063 ms] DevTools activation throttled until 2022-02-08 07:25:07.080987.
```

flutter analyze

```
Analyzing factsforever...                                               

   info • The value of the field '_firestore' isn't used •
          lib/services/cloud_firestore_service.dart:6:21 • unused_field
   info • Unused import: 'package:factsforever/screens/navbar_screen.dart' •
          lib/services/firebase_auth_service.dart:2:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' •
          lib/services/firebase_auth_service.dart:5:8 • unused_import
   info • The exception variable 'err' isn't used, so the 'catch' clause can be
          removed • lib/services/firebase_auth_service.dart:184:38 •
          unused_catch_clause
   info • Unused import: 'dart:typed_data' •
          lib/services/firebase_storage_service.dart:2:8 • unused_import
   info • The exception variable 'e' isn't used, so the 'catch' clause can be
          removed • lib/services/firebase_storage_service.dart:21:35 •
          unused_catch_clause

6 issues found. (ran in 124.0s)
```

**Comment by maheshmnj** [comment]
Hi @dudeismail, Thanks for filing the issue. Please share a minimal and complete code sample to reproduce the issue.

Thanks

**Comment by dudeismail** [comment]
@maheshmnj  thanks for your response, but how can i give the code that is inetegrated with lot of other screens and packages?

**Comment by maheshmnj** [comment]
@dudeismail You can create a  [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example)  by creating a new project and adding a reproducible code from your project. Verify that the issue is reproducible in a newly created project and then share the code sample.

Please refer to the above link on how to share a complete reproducible sample code.

**Comment by minhdanh** [comment]
Hi @ismaildudekula, I'm having this problem too. Could you find a solution for it?
