### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by PaulRudin** [googleads/googleads-mobile-flutter#536]
## Plugin Version

  google_mobile_ads: ^1.1.0

## Steps to Reproduce

This is difficult to reproduce reliably as it only happens on certain devices. I speculate that depends on the ad being served, but it's hard to know for sure.
**Expected results:** 
I expect ads to be served (as is normally the case)
**Actual results:** 
On some occasions the app crashes. Here's a backtrace:
```
java.lang.NullPointerException: 	at com.xamaral.liveff.ListTileNativeAdFactory.createNativeAd(ListTileNativeAdFactory.java:125)
	at io.flutter.plugins.googlemobileads.FlutterNativeAd.onNativeAdLoaded(FlutterNativeAd.java:4)
	at io.flutter.plugins.googlemobileads.FlutterNativeAdLoadedListener.onNativeAdLoaded(FlutterNativeAdLoadedListener.java:16)
	at com.google.android.gms.internal.ads.zzbyp.zze(zzbyp.java:7)
	at com.google.android.gms.internal.ads.zzbnj.zzbT(zzbnj.java:31)
	at com.google.android.gms.internal.ads.zzow.onTransact(zzow.java:20)
	at android.os.Binder.transact(Binder.java:1100)
	at ahm.bj(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:2)
	at com.google.android.gms.ads.internal.formats.client.ak.e(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:0)
	at com.google.android.gms.ads.nonagon.ad.nativead.ae.run(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at auj.a(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:0)
	at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:1)
	at auj.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:0)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)
```

<details>
  <summary>Logs</summary>

I can't reproduce the issue on my own devices or emulators, but the play console shows this backtrace.
```
```

The only analysis issues are to do with camel case conventions.

```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 21.10 5.13.0-23-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.3 at /home/paul/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/paul/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/paul/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/paul/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • SM G935F (mobile) • 9885b6493733464938 • android-arm64  • Android 8.0.0 (API 26)
    • Linux (desktop)   • linux              • linux-x64      • Ubuntu 21.10 5.13.0-23-generic
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by maheshmnj** [comment]
Hi @PaulRudin, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

**Comment by PaulRudin** [comment]
As I said, I can't reproduce the issue on demand. I know it's happening because the google play console reports (some) app crashes with tracebacks, which is where I got the above backtrace from. The same code runs perfectly well on many devices. (My speculation is that it's data dependent - i.e. depends on actual advert; but I'm not sure how I'd verify that.)

**Comment by PaulRudin** [comment]
Incidentally - the bottom of the traceback looks similar to this: https://groups.google.com/g/google-admob-ads-sdk/c/rCZMplesYEc?pli=1
Someone from the admob sdk team there says that it's "known issue", but it looks like it's been around for at least a couple of years. Maybe this is a red herring anyhow?

**Comment by maheshmnj** [comment]
Thanks for the info @PaulRudin, Can you please clarify if this happens with test ads or real ads, Also Can you name the affected devices (where the issue reproduces).

**Comment by PaulRudin** [comment]
This is with real ads. The only device that it's happened on is a Samsung Galaxy s10 running Android 12 (SDK 31). It seems that the crash happened in quick succession several times - almost certainly the same user. 

This is newly released app, so there are very few users at the moment.

I'll add crashlytics for the next release of the app, which maybe will provide more information - assuming I see some more occurrences of the crash.

**Comment by maheshmnj** [comment]
Thanks for the info @PaulRudin, Labeling this issue for further investigation.

**Comment by jjliu15** [comment]
Based on the stack trace, it looks like the NPE occurs somewhere within `ListTileNativeAdFactory`. @PaulRudin could you share a code sample for `ListTileNativeAdFactory`?

**Comment by PaulRudin** [comment]
Ah, OK; quite possibly it's not a bug in the package in that case. Anyway, the code below is below and is taken from the following codelab: https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7 (the kotlin bit)

```kotlin
package com.xamaral.example

import android.content.Context
import android.view.LayoutInflater
import android.view.View
import android.widget.ImageView
import android.widget.TextView

import com.google.android.gms.ads.nativead.NativeAd
import com.google.android.gms.ads.nativead.NativeAdView
import io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin

class ListTileNativeAdFactory(val context: Context) : GoogleMobileAdsPlugin.NativeAdFactory {

    override fun createNativeAd(
        nativeAd: NativeAd,
        customOptions: MutableMap<String, Any>?
    ): NativeAdView {
        val nativeAdView = LayoutInflater.from(context)
            .inflate(R.layout.list_tile_native_ad, null) as NativeAdView

        with(nativeAdView) {
            val attributionViewSmall =
                findViewById<TextView>(R.id.tv_list_tile_native_ad_attribution_small)
            val attributionViewLarge =
                findViewById<TextView>(R.id.tv_list_tile_native_ad_attribution_large)

            val iconView = findViewById<ImageView>(R.id.iv_list_tile_native_ad_icon)
            val icon = nativeAd.icon
            if (icon != null) {
                attributionViewSmall.visibility = View.VISIBLE
                attributionViewLarge.visibility = View.INVISIBLE
                iconView.setImageDrawable(icon.drawable)
            } else {
                attributionViewSmall.visibility = View.INVISIBLE
                attributionViewLarge.visibility = View.VISIBLE
            }
            this.iconView = iconView

            val headlineView = findViewById<TextView>(R.id.tv_list_tile_native_ad_headline)
            headlineView.text = nativeAd.headline
            this.headlineView = headlineView

            val bodyView = findViewById<TextView>(R.id.tv_list_tile_native_ad_body)
            with(bodyView) {
                text = nativeAd.body
                visibility = if (nativeAd.body.isNotEmpty()) View.VISIBLE else View.INVISIBLE
            }
            this.bodyView = bodyView

            setNativeAd(nativeAd)
        }

        return nativeAdView
    }
}
```

**Comment by jjliu15** [comment]
It looks like the NPE happens when `FlutterNativeAd` calls `ListTileNativeAdFactory.createNativeAd`. The stack trace shows it coming from `ListTileNativeAdFactory.java:125`, but it's unclear what line that would be from the code snippet. Maybe `nativeAd.body` is null?

**Comment by jjliu15** [comment]
@01588 could you share your stack traces?

**Comment by thanhnamitit** [comment]
I'm facing the same issue, the problem is I override createNativeAd function with customOptions nonnullable. I changed it to nullable and It work well

**Comment by glintpursuit** [comment]
@PaulRudin @thanhnamitit @jjliu15 
Did you guys able to resolve the issue, facing exactly same issue.
