### ISSUE TITLE
[Production]Error: Caused by java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfUrlConnection" 

### ISSUE THREAD

**Issue by ycv005** [googleads/googleads-mobile-flutter#556]
## Plugin Version
 google_mobile_ads: ^1.2.0

## Steps to Reproduce

1. Add mopub mediation to the application ([setup_link](https://developers.google.com/admob/android/mediation/mopub)), but after seeing the error logs from my production app, I remove that mopub, and re-deploy new application version but still getting same error.

**Expected results:** 

**Actual results:** 

## Bug report
Does this error is due to the firebase_core or firebase_performance(i didn't using this one.)
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/perf/network/FirebasePerfUrlConnection;
       at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:189)
       at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:207)
       at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:88)
       at com.mopub.network.MoPubRequestQueue$volleyHurlStack$1.executeRequest(MoPubRequestQueue.java:48)
       at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
       at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
       at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
       at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```
```
Caused by java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.perf.network.FirebasePerfUrlConnection" on path: DexPathList[[zip file "/data/app/com.example-1/base.apk", zip file "/data/app/com.example-1/split_config.armeabi_v7a.apk", zip file "/data/app/com.example-1/split_config.bn.apk", zip file "/data/app/com.example-1/split_config.en.apk", zip file "/data/app/com.example-1/split_config.gu.apk", zip file "/data/app/com.example-1/split_config.hi.apk", zip file "/data/app/com.example-1/split_config.kn.apk", zip file "/data/app/com.example-1/split_config.mr.apk", zip file "/data/app/com.example-1/split_config.ta.apk", zip file "/data/app/com.example-1/split_config.te.apk", zip file "/data/app/com.example-1/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.example-1/lib/arm, /data/app/com.example-1/base.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.bn.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.gu.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.hi.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.kn.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.mr.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.ta.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.te.apk!/lib/armeabi-v7a, /data/app/com.example-1/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.mopub.volley.toolbox.HurlStack.createConnection(HurlStack.java:189)
       at com.mopub.volley.toolbox.HurlStack.openConnection(HurlStack.java:207)
       at com.mopub.volley.toolbox.HurlStack.executeRequest(HurlStack.java:88)
       at com.mopub.network.MoPubRequestQueue$volleyHurlStack$1.executeRequest(MoPubRequestQueue.java:48)
       at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:91)
       at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
       at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
       at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

**Describe the bug**
Below bugs are reported by the firebase crashlytics and shown in my Production App.
Even though, I am not using the mopub in this current version of my app which has reported the error. (earlier, I was using Admob mediation with mopub, but remove mopub after seeing this error, & remove it from build.gradle file) and currenlty only using below config.

```
dependencies {
    implementation 'com.facebook.android:facebook-login:latest.release'
    implementation 'com.google.android.gms:play-services-safetynet:18.0.1'
    implementation 'com.google.android.gms:play-services-ads:20.6.0'
    implementation 'com.google.ads.mediation:facebook:6.10.0.0'
    // implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
}
```

**Comment by maheshmnj** [comment]
Hi @ycv005, Thanks for filing the issue. 

> Below bugs are reported by the firebase crashlytics and shown in my Production App.

Is this issue not reproducible locally? if it does can you share a minimal sample code?

**Comment by ycv005** [comment]
Hello @maheshmnj I didn't face this issue locally. So, for now, I don't have idea to reproduce it locally.

**Comment by maheshmnj** [comment]
> Hello @maheshmnj I didn't face this issue locally. So, for now, I don't have idea to reproduce it locally.

Thanks for the info Labeling this issue for further insights from the team. Incase you have any further info for us feel free to add it in this issue thread.

**Comment by huycozy** [comment]
We’re closing this issue due to inactivity. If you’re still impacted, please create a new issue via the [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).
