### ISSUE TITLE
GADInvalidInitializationException crash even when we don't use package

### ISSUE THREAD

**Issue by devibrahimkarahan** [googleads/googleads-mobile-flutter#572]
## Plugin Version

1.2.0

## Steps to Reproduce

1. Run `flutter create bug`
2. Add this package to dependencies
3. Run app without adding any ID or code, just add package and run
4. Oops, crash
`'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'`

**Expected results:**
Im expect the application to run without crash. Because i just add the package, **didnt write any initialize code yet `MobileAds.instance.initialize()`.**

If i was using `MobileAds.instance.initialize()` this initialize code, crash is ok by the way.

For example, i need to use admob just for android. This happened to me before and i created an app id for ios that i will never use.
For now, i want to use this package into my core package, some projects can use admob, but some projects may will never use admob.

**Actual results:**
Crash

<details>
  <summary>Logs</summary>

```
[   +1 ms] Application launched on the device. Waiting for observatory url.
[+1941 ms] (lldb) 2022-05-24 13:21:01.577854+0300 Runner[2870:1060884] FFmpegKitFlutterPlugin 0x280ff77a0 created.
[   +3 ms] 8.11.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
[  +15 ms] 8.11.0 - [Firebase/Analytics][I-ACS025028] AdMob and Firebase are in use in this app, but are not linked. For analytics data consistency and integrity, it is highly recommended that you link your AdMob app to the
corresponding Firebase app and re-download the GoogleServices-Info.plist file. See https://support.google.com/admob/answer/6383165 for more information.
[ +142 ms] 8.11.0 - [Firebase/Analytics][I-ACS023007] Analytics v.8.11.0 started
[        ] 8.11.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[  +20 ms] *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at
https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'
[        ] *** First throw call stack:
[        ] (0x180fedcac 0x19805c758 0x1810b74a8 0x102fac7a4 0x102f5b828 0x180cb92ec 0x180cba2f0 0x180c91698 0x180c9e488 0x180c9ec5c 0x1da8d6efc 0x1da8d6aa4)
[        ] libc++abi: terminating with uncaught exception of type NSException
[ +321 ms] Process 2870 stopped
[   +2 ms] * thread #3, queue = 'com.apple.root.default-qos', stop reason = signal SIGABRT
[        ]     frame #0: 0x00000001ba4c2a48 libsystem_kernel.dylib`__pthread_kill + 8
[        ] libsystem_kernel.dylib`__pthread_kill:
[        ] ->  0x1ba4c2a48 <+8>:  b.lo   0x1ba4c2a64               ; <+36>
[        ]     0x1ba4c2a4c <+12>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x1ba4c2a50 <+16>: mov    x29, sp
[        ]     0x1ba4c2a54 <+20>: bl     0x1ba4be6d0               ; cerror_nocancel
[        ] Target 0: (Runner) stopped.
[   +5 ms] ios-deploy exited with code 0
[  +15 ms] Installing and launching... (completed in 47,0s)
[   +1 ms] Error launching application on  iPhone X.
[  +11 ms] "flutter run" took 92.171ms.
[  +17 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +205 ms] ensureAnalyticsSent: 199ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
Analyzing baseproject...                                                
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2 21D49 darwin-arm, locale tr)
    • Flutter version 2.10.4 at /Users/X/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (9 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/X/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    •  iPhone X (mobile) • 369e6d797f6304ce3324c410d46fdd31689f6f74 • ios            • iOS 15.0.2 19A404
    • Chrome (web)       • chrome                                   • web-javascript • Google Chrome 101.0.4951.64
    ! Error:  iPhone X is busy: Fetching debug symbols for  iPhone X. Xcode will continue when  iPhone X is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jjliu15** [comment]
This is a behavior enforced by the iOS GMA SDK dependency. It's not designed to be included in your app unless you have an actual admob app id.

One possible workaround for you is to fork the repo and just delete all the iOS platform code and remove the iOS dependencies.

**Comment by cankarabag** [comment]
Is there an update that without removing all the iOS platform codes and iOS dependencies on the forked repo?
