### ISSUE TITLE
[Android 12] Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.content.pm.PackageManager$OnChecksumsReadyListener.onChecksumsReady(java.util.List)"

### ISSUE THREAD

**Issue by zhonghanwen** [googleads/googleads-mobile-flutter#589]
## Plugin Version

google_mobile_ads: ^1.2.0

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Android 12: FlutterAdLoader.loadNativeAd don't crash.**

**Actual results:** 
```
Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.content.pm.PackageManager$OnChecksumsReadyListener.onChecksumsReady(java.util.List)"
       at android.app.ApplicationPackageManager$2.onChecksumsReady(ApplicationPackageManager.java:1016)
       at android.content.pm.IOnChecksumsReadyListener$Stub.onTransact(IOnChecksumsReadyListener.java:87)
       at android.os.Binder.execTransactInternal(Binder.java:1220)
       at android.os.Binder.execTransact(Binder.java:1179)
```

<details>
  <summary>Logs</summary>

```
main
       at java.util.Collections.emptyList(Collections.java:4478)
       at com.google.android.gms.internal.ads.zzfho.zzc(zzfho.java:6)
       at com.google.android.gms.internal.ads.zzddx.zzb(zzddx.java:15)
       at com.google.android.gms.internal.ads.zzddx.zzc(zzddx.java)
       at com.google.android.gms.internal.ads.zzdby.zzi(zzdby.java:15)
       at com.google.android.gms.internal.ads.zzepu.zzb(zzepu.java:266)
       at com.google.android.gms.internal.ads.zzepi.zzd(zzepi.java:18)
       at com.google.android.gms.internal.ads.zzeoc.zzg(zzeoc.java:3)
       at com.google.android.gms.ads.AdLoader.zza(AdLoader.java:10)
       at com.google.android.gms.ads.AdLoader.loadAd(AdLoader.java:4)
       at io.flutter.plugins.googlemobileads.FlutterAdLoader.loadNativeAd(FlutterAdLoader.java:20)
       at io.flutter.plugins.googlemobileads.FlutterNativeAd.load(FlutterNativeAd.java:48)
       at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:1300)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:18)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0(DartMessenger.java:20)
       at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$R4HPk6oFVb-i-YR_PN9YE6kqx1I.run(-.java:12)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @zhonghanwen, Thanks for filing the issue. Can you please share a minimal and complete code sample to investigate the issue along with the complete output of `flutter run -v` in a text file?

Thanks

**Comment by zhonghanwen** [comment]
@maheshmnj this crash appear firebase  Crashlytics Dashboard. When android12 load native ad that crash, app appear this crash.  
![image](https://user-images.githubusercontent.com/12220537/176623813-ea437df7-ff69-42ef-95f5-23390f9564c9.png)

**Comment by maheshmnj** [comment]
Thanks for the report Could you pleae share the crash report? Also is the crash only in production or can be reproduced locally too?
