### ISSUE TITLE
BannerAd does not react to tap gesture. Exception: Trying to use platform views with API 19, required API level is: 20

### ISSUE THREAD

**Issue by dvoloshyn** [googleads/googleads-mobile-flutter#595]
## Plugin Version

1.3.0

## Steps to Reproduce

1. Create flutter app with minSdkVersion = 19. According to the official docs 19 is the minimum supported version: [quick-start](https://developers.google.com/admob/flutter/quick-start)
2. Display AdWidget(ad: BannerAd(...))
3. Run the app and tap on the banner

**Expected results:** 

Browser is opened with the add information

**Actual results:** 

Nothing happens visually but exception in thrown in the logs with "Trying to use platform views with API 19, required API level is: 20"

<details>
  <summary>Logs</summary>

```
[ +373 ms] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +1 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[  +11 ms] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +4 ms] I/flutter (  778): ----------------------------------------------------
[  +19 ms] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +5 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[   +7 ms] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +4 ms] I/flutter (  778): ----------------------------------------------------
[  +66 ms] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +1 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[        ] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +3 ms] I/flutter (  778): ----------------------------------------------------
[        ] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +5 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[   +2 ms] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +4 ms] I/flutter (  778): ----------------------------------------------------
[   +1 ms] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +1 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[   +1 ms] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +4 ms] I/flutter (  778): ----------------------------------------------------
[   +5 ms] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +2 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[        ] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +3 ms] I/flutter (  778): ----------------------------------------------------
[   +1 ms] I/flutter (  778): ----------------FIREBASE CRASHLYTICS----------------
[   +1 ms] I/flutter (  778): PlatformException(error, java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:395)
[        ] I/flutter (  778):   at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:342)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:199)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:72)
[        ] I/flutter (  778):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] I/flutter (  778):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
[        ] I/flutter (  778):   at android.os
[        ] I/flutter (  778): 
[        ] I/flutter (  778): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
[        ] I/flutter (  778): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #2      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:810:5)
[        ] I/flutter (  778): <asynchronous suspension>
[        ] I/flutter (  778): #3      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:908:7)
[        ] I/flutter (  778): <asynchronous suspension>
[   +4 ms] I/flutter (  778): ----------------------------------------------------
[  +12 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +29 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +286 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 5412K, 48% free 18601K/35464K, paused 61ms, total 62ms
[  +30 ms] E/File    (  778): fail readDirectory() errno=20
[        ] E/File    (  778): fail readDirectory() errno=20
[   +4 ms] E/File    (  778): fail readDirectory() errno=20
[ +241 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 3634K, 48% free 18535K/35464K, paused 60ms, total 60ms
[  +16 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +25 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +173 ms] E/File    (  778): fail readDirectory() errno=20
[        ] E/File    (  778): fail readDirectory() errno=20
[   +5 ms] E/File    (  778): fail readDirectory() errno=20
[ +210 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 3356K, 48% free 18788K/35464K, paused 61ms, total 61ms
[ +141 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +28 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +82 ms] E/File    (  778): fail readDirectory() errno=20
[        ] E/File    (  778): fail readDirectory() errno=20
[   +4 ms] E/File    (  778): fail readDirectory() errno=20
[ +196 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 4872K, 48% free 18777K/35464K, paused 63ms, total 63ms
[ +242 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +12 ms] E/File    (  778): fail readDirectory() errno=20
[        ] E/File    (  778): fail readDirectory() errno=20
[   +4 ms] E/File    (  778): fail readDirectory() errno=20
[  +12 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +121 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 3981K, 48% free 18494K/35464K, paused 59ms, total 59ms
[ +333 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 3469K, 48% free 18497K/35464K, paused 58ms, total 58ms
[  +33 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +36 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[        ] E/File    (  778): fail readDirectory() errno=20
[   +1 ms] E/File    (  778): fail readDirectory() errno=20
[   +5 ms] E/File    (  778): fail readDirectory() errno=20
[ +387 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 5014K, 48% free 18548K/35464K, paused 59ms, total 59ms
[  +54 ms] E/File    (  778): fail readDirectory() errno=20
[        ] E/File    (  778): fail readDirectory() errno=20
[   +5 ms] E/File    (  778): fail readDirectory() errno=20
[  +93 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +45 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +123 ms] D/dalvikvm(  778): GC_FOR_ALLOC freed 3663K, 48% free 18480K/35464K, paused 58ms, total 58ms
[ +188 ms] E/File    (  778): fail readDirectory() errno=20
[        ] E/File    (  778): fail readDirectory() errno=20
[   +4 ms] E/File    (  778): fail readDirectory() errno=20
[ +186 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +42 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +595 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +60 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +525 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +32 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +523 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +48 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +576 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +43 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +532 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +42 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +568 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +53 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +577 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +43 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +511 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +80 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +629 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +36 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +556 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +50 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +556 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +34 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +30 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +557 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +49 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +571 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +65 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +605 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +32 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +559 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +32 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +515 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +64 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +24 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +595 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +42 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +574 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +45 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +578 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[  +41 ms] E/PlatformViewWrapper(  778): Platform view cannot be composed without a surface.
[ +437 ms] I/FIAM.Display(  778): Unbinding from activity: MainActivity
[        ] I/FIAM.Headless(  778): Removing display event component
[   +5 ms] E/FIAM.Display(  778): Activity is finishing or does not have valid window token. Cannot show FIAM.
[ +783 ms] D/dalvikvm(  778): threadid=41: thread exiting, not yet detached (count=0)
[   +2 ms] D/dalvikvm(  778): threadid=51: thread exiting, not yet detached (count=0)
[  +41 ms] W/System  (  778): Ignoring header If-None-Match because its value was null.
[+5485 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///data/data/net.u5dol.worldofgoals/cache/worldofgoalsHZGAIM/worldofgoals/)
[ +252 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +1 ms] "flutter run" took 146,456ms.
[  +94 ms] ensureAnalyticsSent: 92ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
[✓] Flutter (Channel stable, 3.0.4, on Manjaro Linux 5.18.6-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.0.4 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/dvoloshyn/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675
    • Flutter plugin version 67.1.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546
    • Flutter plugin version 67.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/dvoloshyn/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] Connected device (4 available)
    • SM G7102 (mobile)            • 6424f8a5      • android-arm    • Android 4.4.2 (API 19)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Manjaro Linux 5.18.6-1-MANJARO
    • Chrome (web)                 • chrome        • web-javascript • Chromium 103.0.5060.53 Arch Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dvoloshyn** [comment]
Hi @maheshmnj. Sorry, forgot to specify explicitly the most important detail.
You need to actually run it on Android 4.4 (API 19)
I run your code sample in emulator and on a real device with android 4.4.2 and it throws an exception in both cases without opening the browser.
Of course, when running on higher Android versions it works just fine.

**Comment by jjliu15** [comment]
It looks like the minimum supported API level for platform views is 20, and our public documentation needs to be updated to reflect that (it currently says API 19).

There's no workaround since we are limited by platform views. You can still use full screen ads on API 19 and below, but if you need to support banner ads on API 19, you'll need to file a feature request to the Flutter github to extend platform view support to API 19.
