### ISSUE TITLE
Can't find ad with id: 0 when AppOpenAd.show() called.

### ISSUE THREAD

**Issue by LondonX** [googleads/googleads-mobile-flutter#596]
## Plugin Version
google_mobile_ads: ^1.3.0

## Steps to Reproduce
1. Load AppOpenAd with `AppOpenAd.load`.
2. Show AppOpenAd with `AppOpenAd.show`. 
3. Reload new AppOpenAd in `fullScreenContentCallback.onAdDismissedFullScreenContent`.
4. Wait loading success and call `AppOpenAd.show`. 

## My investigation
1. iOS _ads in `FLTAdInstanceManager_internal.m` may not sync with _loadedAds in `ad_instance_manager.dart`, so `adIdFor(ad)` returns the wrong id that not existed in iOS.
2. I did a delay 100ms before reloading in flutter in `fullScreenContentCallback.onAdDismissedFullScreenContent` seems WORKS.
3. Android seems has the same issue, but I have no time to debug in.

**Comment by LondonX** [comment]
@maheshmnj Thanks for replying, I tried your `AppOpenAdManager` class in my app, called `loadAd()` in my app's SplashView, and wait for `onAdLoaded` callback, then navigate to MainView, call `showAdIfAvailable()` in MainView when app goes foreground, and none of callbacks in `fullScreenContentCallback` was getting called, instead, I got some log below:

Android
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(AdShowError, Ad failed to show., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
    <asynchronous suspension>
```

iOS
```
Can't find ad with id: 0
```

**Comment by maheshmnj** [comment]
Thanks for the info @LondonX, Unfortunately, I am unable to reproduce that on my side. Also I do get fullscreenContent callbacks please see the logs below. Can you please share the complete logs of `flutter run -v` in a text file?



Android             |  IOS
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/31410839/177549930-5caa51a0-d2c1-483e-b9dc-5323d142501c.png" width ="300"> | <img src="https://user-images.githubusercontent.com/31410839/177550468-4f228d6e-af0a-462f-8efc-e9304250e32f.png" width ="300"> 



<details>
<summary>logs(Android)</summary>

```dart
Running "flutter pub get" in example...
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:59118/NK0cNwcrDJE=/ws
I/obileadsexampl(12201): The ClassLoaderContext is a special shared library.
I/obileadsexampl(12201): The ClassLoaderContext is a special shared library.
I/DynamiteModule(12201): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:221310604
I/DynamiteModule(12201): Selected remote version of com.google.android.gms.ads.dynamite, version >= 221310604
D/DynamitePackage(12201): Instantiated singleton DynamitePackage.
D/DynamitePackage(12201): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
W/ConnectionStatusConfig(12201): Dynamic lookup for intent failed for action: com.google.android.gms.leibniz.events.service.START
W/GmsClient(12201): unable to connect to service: com.google.android.gms.leibniz.events.service.START on com.google.android.gms
I/WebViewFactory(12201): Loading com.google.android.webview version 101.0.4951.61 (code 495106134)
W/obileadsexampl(12201): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/obileadsexampl(12201): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/obileadsexampl(12201): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/obileadsexampl(12201): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/obileadsexampl(12201): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(12201): Loaded version=101.0.4951.61 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(12201): Successfully loaded native library
I/cr_CachingUmaRecorder(12201): Flushed 9 samples from 9 histograms.
W/obileadsexampl(12201): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
D/HostConnection(12201): HostConnection::get() New Host Connection established 0xb400007a203cb950, tid 12359
I/obileadsexampl(12201): Waiting for a blocking GC ProfileSaver
D/HostConnection(12201): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
W/cr_media(12201): Requires BLUETOOTH permission
D/EGL_emulation(12201): eglCreateContext: 0xb400007a103fce40: maj 3 min 0 rcv 3
D/EGL_emulation(12201): eglMakeCurrent: 0xb400007a103fce40: ver 3 0 (tinfo 0xb4000079b0446820) (first time)
I/Choreographer(12201): Skipped 109 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(12201): Davey! duration=1876ms; Flags=0, IntendedVsync=15326150401105, Vsync=15327967067699, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=15327967345725, AnimationStart=15327967348600, PerformTraversalsStart=15327967614391, DrawStart=15327969259016, SyncQueued=15327970300683, SyncStart=15327971823266, IssueDrawCommandsStart=15327981388308, SwapBuffers=15328012862433, FrameCompleted=15328028344725, DequeueBufferDuration=1978833, QueueBufferDuration=2368750, GpuCompleted=0,
D/EGL_emulation(12201): eglCreateContext: 0xb400007a103fc6b0: maj 3 min 0 rcv 3
D/DynamitePackage(12201): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (12201): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("37B2E83F0935251E53408AEA377C62CD")) to get test ads on this device.
D/EGL_emulation(12201): eglCreateContext: 0xb400007a10449e40: maj 3 min 0 rcv 3
W/Ads     (12201): Not retrying to fetch app settings
D/EGL_emulation(12201): eglCreateContext: 0xb400007a1044f590: maj 3 min 0 rcv 3
D/EGL_emulation(12201): eglCreateContext: 0xb400007a1044eb40: maj 3 min 0 rcv 3
I/DynamiteModule(12201): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:221310604
I/DynamiteModule(12201): Selected remote version of com.google.android.gms.ads.dynamite, version >= 221310604
I/flutter (12201): Instance of 'AppOpenAd' loaded
D/DynamitePackage(12201): Instantiating com.google.android.gms.ads.ChimeraAdOverlayCreatorImpl
I/flutter (12201): Instance of 'AppOpenAd' onAdShowedFullScreenContent
W/Ads     (12201): A GMSG tried to close something that wasn't an overlay.
W/Ads     (12201): #004 The webview is destroyed. Ignoring action.
I/flutter (12201): Instance of 'AppOpenAd' onAdDismissedFullScreenContent
W/Ads     (12201): #004 The webview is destroyed. Ignoring action.
D/DynamitePackage(12201): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (12201): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("37B2E83F0935251E53408AEA377C62CD")) to get test ads on this device.
D/EGL_emulation(12201): eglCreateContext: 0xb400007a10462db0: maj 3 min 0 rcv 3
I/DynamiteModule(12201): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:221310604
I/DynamiteModule(12201): Selected remote version of com.google.android.gms.ads.dynamite, version >= 221310604
I/flutter (12201): Instance of 'AppOpenAd' loaded

```
</details> 

<details>
<summary>logs (IOS)</summary>

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Upgrading Info.plist
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                           45.3s
 - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-3940256099942544~1458002511
 - <Google>[I-ACS023007] Analytics v.80901000 started
 - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
 - <Google>[I-ACS023171] Resetting App Measurement data
 - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/Users/mahesh/Library/Developer/CoreSimulator/Devices/C217DCBE-806E-4BC7-A952-61E4A647A7DA/data/Containers/Data/Application/1D39A7B5-E7AF-4092-89F1-DD141DABF359/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x6000033d4630 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Connecting to VM Service at ws://127.0.0.1:59879/_eZVNII05yo=/ws
 - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
<Google> To get test ads on this device, set:
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ kGADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ kGADSimulatorID ]
 - <Google>[I-ACS023012] Analytics collection enabled
flutter: Instance of 'AppOpenAd' loaded
flutter: Instance of 'AppOpenAd' onAdShowedFullScreenContent
 - <Google>[I-ACS023130] Configuration not found. Using default configuration
flutter: Instance of 'AppOpenAd' onAdDismissedFullScreenContent
flutter: Instance of 'AppOpenAd' loaded

```
</details>

**Comment by LondonX** [comment]
@maheshmnj Thanks for replying, but I am not allowed to share the full log 😂, as we are going to release app soon, I made a try-catch out the `AppOpenAd.show` 😂😂, once catched, dispose the loaded and reload immediately, and wait for next showing, absolutely not resolved but  it works so far, and I will keep watching this issue.

**Comment by BriceFab** [comment]
@LondonX @maheshj01 Adding a try catch to AppOpenAd.show won't work for me.

https://github.com/googleads/googleads-mobile-flutter/issues/1266
