### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [googleads/googleads-mobile-flutter#614]
I am using `google_mobile_ads: ^1.3.0` in project and using correct ad ID but having this fetal exception.
Now I am running another GitHub project which also giving same issue.
All logs are:

` FATAL EXCEPTION: main
E/AndroidRuntime(15597): Process: com.example.flutter_google_ads, PID: 15597
E/AndroidRuntime(15597): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
E/AndroidRuntime(15597):
E/AndroidRuntime(15597): ******************************************************************************
E/AndroidRuntime(15597): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(15597): * should follow the instructions here:                                       *
E/AndroidRuntime(15597): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(15597): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(15597): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(15597): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(15597): ******************************************************************************
2
E/AndroidRuntime(15597):
E/AndroidRuntime(15597): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
E/AndroidRuntime(15597): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
E/AndroidRuntime(15597): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
E/AndroidRuntime(15597): 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
E/AndroidRuntime(15597): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
E/AndroidRuntime(15597): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15597): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(15597): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(15597): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15597): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(15597): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(15597): Caused by: java.lang.IllegalStateException:
E/AndroidRuntime(15597):
E/AndroidRuntime(15597): ******************************************************************************
E/AndroidRuntime(15597): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(15597): * should follow the instructions here:                                       *
E/AndroidRuntime(15597): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(15597): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(15597): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(15597): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(15597): ******************************************************************************
2
E/AndroidRuntime(15597):
E/AndroidRuntime(15597): 	at com.google.android.gms.internal.ads.zzacz.attachInfo(com.google.android.gms:play-services-ads-lite@@20.1.0:20)`

**Comment by huycozy** [comment]
Hi @UmairSaqibBhutta 
I see there's an issue addressing the case you described #454 and look at https://github.com/googleads/googleads-mobile-flutter/issues/454#issuecomment-984913012 that provided the solution for this.
Let's try it and confirm if the issue can be fixed or not.

**Comment by UmairSaqibBhutta** [comment]
@huycozy issue #454 solved by removing `meta `tag from `activity `tag in manifest.java file.
But I have already added:
` <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxx~yyyyyyyyyyyy"/>`

outside of `activity` tag.

**Comment by huycozy** [comment]
@UmairSaqibBhutta 
Do you put the `meta-data` tag inside `application` tag like this?
https://github.com/googleads/googleads-mobile-flutter/blob/a10c6153e1d93aa3f1e0c54b9e4113f3fe5188a9/packages/google_mobile_ads/example/android/app/src/main/AndroidManifest.xml#L6-L22


Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by UmairSaqibBhutta** [comment]
s h

**Comment by UmairSaqibBhutta** [comment]
my `flutter doctor -v` is:

[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19042.1766], locale en-US)
PS E:\WorkingProjects\KindnessAppNew> flutter doctor -v
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19042.1766], locale en-US)
    • Flutter version 3.0.2 at E:\flutter_windows_3.0.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (7 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Umair\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\Umair\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.71

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

`manifest.java` is:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app.kindnessapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    

    <queries>
        
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.SENDTO" />
            <data android:scheme="smsto" />
        </intent>
        
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
    <application
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:label="Kindness">
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxxx"/>
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        

            
    </application>
</manifest>
`

1. Dart code in `main`:

`MobileAds.instance.initialize();`


2.  Banner method is:
`  void loadStaticBannerAd() {
    staticAd = BannerAd(
        // Change Banner Size According to Ur Need
        size: AdSize.banner,
        adUnitId: getBannerAdUnitId(),
        listener: BannerAdListener(onAdLoaded: (_) {
          setState(() {
            isBannerLoaded = true;
          });
          log("banner loaded successfully");
        }, onAdFailedToLoad: (ad, LoadAdError error) {
          log("Failed to Load A Banner Ad${error.message}");
          ad.dispose();
        }),
        request: const AdRequest())
      ..load();
  }`

3. Dart code where I am showing banner is:
`if (isBannerLoaded)
                Container(
                  padding: const EdgeInsets.only(bottom: 5),
                  width: staticAd.size.width.toDouble(),
                  height: staticAd.size.height.toDouble(),
                  child: AdWidget(
                    ad: staticAd,
                  ),
                ),`

**Comment by UmairSaqibBhutta** [comment]
I upgraded flutter version to `3.0.5`.
I tried running [example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and it worked.
Then I copied example code into my project even with same banner Id but app stuck on installing.
I tried 3,4 times again with `flutter clean` but it never worked.

**Comment by huycozy** [comment]
@UmairSaqibBhutta 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. It will be better if you push your sample code into an open source repository (such as GitHub) and then share it here. Thanks!

**Comment by UmairSaqibBhutta** [comment]
I replaced your testing adUnitId in my project and it worked but why my adUnitId not working?
Now I created new adUnitId for releasae version but not worked.
Any solution please ?

**Comment by huycozy** [comment]
@UmairSaqibBhutta 
>I replaced your testing adUnitId in my project and it worked but why my adUnitId not working?
Now I created new adUnitId for releasae version but not worked.
Any solution please ?

When you replace it with release adUnitId, does the exception still occur? Or is the ads just not showing up?

**Comment by NemanjaCvetkovic1993** [comment]
> The issue was in my code. I fixed it. Thanks for your help. Thanks alot again ❤️.

Can you let us know what was the problem with the code? I am facing the same issue. And since I have couple of projects, I tried 2 and both have the same error.

**Comment by UmairSaqibBhutta** [comment]
I was using the same ad id in the manifest and code.

**Comment by NemanjaCvetkovic1993** [comment]
> I was using the same ad id in the manifest and code.

I made the exact same mistake. And it was such a dumb mistake, I should have known. But luckily, I didn't spend much time figuring it out.

**Comment by BigTexApps** [comment]
Not sure why that would cause the problem? What ad id should i use in the manifest and what should i use in the activity where Im running the ad?

**Comment by deepesh-inoid** [comment]
> <meta-data 
>          android:name="com.google.android.gms.ads.APPLICATION_ID" 
>          android:value="ca-app-pub-3940256099942544~3347511713"/>

Thankyou Its Working
