### ISSUE TITLE
Not showing ad with real device (Google Pixel 6a).

### ISSUE THREAD

**Issue by hukusuke1007** [googleads/googleads-mobile-flutter#642]
## Plugin Version

2.0.1

## Steps to Reproduce

1. Run app.
2. Showing Ad Widget.
3. Error occur. Please see the following Logs.

But, It works in the simulator.

**Expected results:** 
Not showing ad.

**Actual results:** 

Showing Ad.

<details>
  <summary>Logs</summary>

```
E/MethodChannel#flutter/platform_views(18675): Failed to handle method call
E/MethodChannel#flutter/platform_views(18675): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(18675): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(18675): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(18675): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(18675): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views(18675): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views(18675): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/MethodChannel#flutter/platform_views(18675): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(18675): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views(18675): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter (18675): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (18675): PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
I/flutter (18675): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
I/flutter (18675): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
I/flutter (18675): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
I/flutter (18675): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
I/flutter (18675): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (18675): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (18675): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(Dart
I/flutter (18675): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter (18675): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter (18675): <asynchronous suspension>
I/flutter (18675): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
I/flutter (18675): <asynchronous suspension>
I/flutter (18675): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
I/flutter (18675): <asynchronous suspension>
I/flutter (18675): ----------------------------------------------------
```

```
```

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale
    ja-JP)
    • Flutter version 3.3.1 on channel stable at
      /Users/shohei/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (2 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/shohei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at
      /Applications/Xcode-14.0.0-Release.Candidate.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Pixel 6a (mobile)           • 24061JEGR14069 • android-arm64  • Android 12
      (API 32)
    • sdk gphone64 arm64 (mobile) • emulator-5554  • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos          • darwin-arm64   • macOS
      12.5.1 21G83 darwin-arm
    • Chrome (web)                • chrome         • web-javascript • Google
      Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @hukusuke1007
Is this issue reproducible locally? If so, please try running [example code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and share the output of `flutter run -v` so that we may verify the issue.

**Comment by hukusuke1007** [comment]
It was the same as this issue.
https://github.com/googleads/googleads-mobile-flutter/issues/59

```
I/flutter (25339): bannerAd failedToLoad: LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))
```

**Comment by huycozy** [comment]
Hi @hukusuke1007, in case you are having issue #59, please follow up on it for further updates.  You can leave there your comment and react an upvote to the original comment will help to raise the issue. 
Closing this issue as a duplicate. Thank you!
