### ISSUE TITLE
Flightmode (no internet connection) shows a grey box and no updates in the state

### ISSUE THREAD

**Issue by large** [googleads/googleads-mobile-flutter#669]
## Plugin Version
2.1.0

## Steps to Reproduce
Using mac as dev machine. Have not tested on a windows machine.
Use "Network Link conditioner" and turn on "100% loss". (Link to tool: https://nshipster.com/network-link-conditioner/ )

Loading banner with this, see adstate class in "expected result" to see that handler:

<details>
<summary>Sample code</summary>

```dart
class BannerAD extends StatefulWidget {
  final AnchoredAdaptiveBannerAdSize? sizeOverride;

  const BannerAD({Key? key, this.sizeOverride}) : super(key: key);

  @override
  BannerADState createState() => BannerADState();
}

class BannerADState extends State<BannerAD> with WidgetsBindingObserver {
  BannerAd? banner;

  AnchoredAdaptiveBannerAdSize? size;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if(state == AppLifecycleState.resumed)
      {
        setState(() {});
        debugPrint("We are resuming ads now...");
      }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
    banner?.dispose();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    // Initialising adState here because it need context
    // and didChangeDependencies() is called few moments after the state loads its dependencies
    // so context is available at this moment.
    final adState = Provider.of<AdState>(context);

    adState.initialization.then((value) async {
      // Assigning the size of adaptive banner ad after adState initialization.
      size = await anchoredAdaptiveBannerAdSize(context);

      if (widget.sizeOverride != null) {
        size = widget.sizeOverride;
      }

      //No size, just return...
      if(size == null) {
        return;
      }

      setState(() {
        // If adState.bannerAdUnitId is null don't create a BannerAd.
        try
        {
          banner = BannerAd(
            listener: adState.adListener,
            adUnitId: AdHelper.bannerAdUnitId,
            request: const AdRequest(),
            size: size!,
          )..load();
          debugPrint("banner load...");
        }
        catch(e)
        {
          debugPrint("**************** BannerAd error ${e.toString()}");
        }
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    //Set width based on input or default width

    //Status of the actual ad
    bool showAd = AdState.adStatus;

    if (banner == null) {
      // Generally banner is null for very less time only until it get assigned in didChangeDependencies.
      // Never think that banner will be null if ads fails loads.
      // To make banner null change the condition in didChangeDependencies or assign null to bannerAdUnitId in AdState().
      return const AdAlternativeSizedBox();
    } else {
      //Handle size given (if no ad is given)
      Size bannerSize = Size(size!.width.toDouble(), size!.height.toDouble());
      if(bannerSize.width == 0) bannerSize = const Size(320, 50);

      try
      {
        Widget ad = Container(
          color: showAd ? Colors.grey : Colors.transparent,
          width: showAd ? bannerSize.width.toDouble() : 320,
          height: showAd ? bannerSize.height.toDouble() : 50,
          child: showAd
          // If AdState.adStatus is true then ads loads
          // but if its false it will display a empty sizedBox.
              ? AdWidget(
            ad: banner!,
          )
              : const AdAlternativeSizedBox(),
        );

        return ad;
      }
      catch(e)
      {
//Errhandler
      }
    }
  }
Future<AnchoredAdaptiveBannerAdSize?> anchoredAdaptiveBannerAdSize(
    BuildContext context) async {
  // Used to set size of adaptive banner ad according to device width and orientation.
  return await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
      MediaQuery.of(context).size.width.toInt());
}

}
```

</details>

**Expected results:** 
That the adstate of onAdFailedToLoad was called after timeout, not an uncaught system exception after 60s.
 
```dart
class AdState {
  Future<InitializationStatus> initialization;
  AdState(this.initialization);

  static bool adStatus = true;

  AdManagerBannerAdListener get adListener => _adListener;

  final AdManagerBannerAdListener _adListener = AdManagerBannerAdListener(
    // Called when an ad is successfully received.
    onAdLoaded: (Ad ad) {
      debugPrint('**************** Ad loaded.');
      adStatus = true;
    },
    // Called when an ad request failed.
    onAdFailedToLoad: (Ad ad, LoadAdError error) {
      // Dispose the ad here to free resources.
      ad.dispose();
      debugPrint('**************** Ad failed to load: $error case ${error.message}');
      adStatus = false;
    },
    // Called when an ad opens an overlay that covers the screen.
    onAdOpened: (Ad ad) => debugPrint('**************** Ad opened.'),
    // Called when an ad removes an overlay that covers the screen.
    onAdClosed: (Ad ad) => debugPrint('**************** Ad closed.'),
    // Called when an impression occurs on the ad.
    onAdImpression: (Ad ad) =>
        debugPrint('**************** Ad impression.'),
    onAppEvent: (ad, name, data) =>
        debugPrint('**************** App event : ${ad.adUnitId}, $name, $data.'),
  );
}
```
**Actual results:** 
I see the "banner loaded" called, then after a while this uncaught exception.

<details>
  <summary>Logs</summary>

```
[+60466 ms] 
                     ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                     The following _TypeError was thrown during a platform message callback:
                     type 'Null' is not a subtype of type 'String'
                     
                     When the exception was thrown, this was the stack:
                     #0      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1007:31)
                     #1      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1003:38)
                     #2      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1022:11)
                     #3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479:12)
                     #4      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:531:39)
                     #5      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1108:22)
                     #6      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479:12)
                     #7      StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:612:44)
                     #8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:534:35)
                     #9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
                     #10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
                     #11     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
                     #15     _invoke2 (dart:ui/hooks.dart:188:10)
                     #16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
                     #17     _Channel.push (dart:ui/channel_buffers.dart:132:31)
                     #18     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
                     #19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
                     #20     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
                     (elided 3 frames from dart:async)
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
• No issues found!
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-NO)
    • Flutter version 3.3.4 on channel stable at /Users/large/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (12 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/large/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • B933F8E9-818A-429A-ACE6-33FF24F33575 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @large 

>That the adstate of onAdFailedToLoad was called after timeout, not an uncaught system exception after 60s.

Can you explain more about this and detailed steps to reproduce the issue when using `Network Link conditioner`?

Also, your sample code still is not completed. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by large** [comment]
I figured out what was wrong with my implementation. Using a static variable as "bannerloaded" did not work as intended.
