### ISSUE TITLE
Permission Denial: starting Intent / Application (which i guess those app is not exported)

### ISSUE THREAD

**Issue by hmduc1603** [googleads/googleads-mobile-flutter#690]
I've encountered crashes when user click on open_add

**_Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://www.googleadservices.com/... flg=0x10000000 cmp=com.casttv.castforchromecast.screencast/com.thntech.cast68.screen.tab.webcast.WebCastActivity } from ProcessRecord{fcdee92 26926:chromecast.tv.setup/u0a256} (pid=26926, uid=10256) not exported._**

## Plugin Version

google_mobile_ads: ^2.2.0

<details>
<summary>Stack trace</summary>

```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://www.googleadservices.com/... flg=0x10000000 cmp=com.casttv.castforchromecast.screencast/com.thntech.cast68.screen.tab.webcast.WebCastActivity } from ProcessRecord{fcdee92 26926:chromecast.tv.setup/u0a256} (pid=26926, uid=10256) not exported from uid 10241
       at android.os.Parcel.createException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3690)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
       at android.app.Activity.startActivityForResult(Activity.java:4684)
       at android.app.Activity.startActivityForResult(Activity.java:4639)
       at android.app.Activity.startActivity(Activity.java:5003)
       at android.app.Activity.startActivity(Activity.java:4971)
       at com.google.android.gms.ads.internal.webview.aw.startActivity(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:1)
       at com.google.android.gms.ads.internal.util.q.S(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:2)
       at com.google.android.gms.ads.internal.util.q.M(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:4)
       at com.google.android.gms.ads.internal.overlay.a.a(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:3)
       at com.google.android.gms.ads.internal.overlay.a.b(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:3)
       at com.google.android.gms.ads.internal.overlay.l.a(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:12)
       at com.google.android.gms.ads.internal.webview.q.m(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:3)
       at com.google.android.gms.ads.internal.webview.q.l(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:3)
       at com.google.android.gms.ads.internal.webview.ac.aA(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314)
       at com.google.android.gms.ads.internal.webview.y.aA(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314)
       at com.google.android.gms.ads.internal.gmsg.ar.h(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:24)
       at com.google.android.gms.ads.internal.gmsg.ar.e(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:72)
       at com.google.android.gms.ads.internal.gmsg.ar.a(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314)
       at com.google.android.gms.ads.internal.webview.q.B(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:4)
       at com.google.android.gms.ads.internal.webview.q.e(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:8)
       at com.google.android.gms.ads.internal.webview.q.shouldOverrideUrlLoading(:com.google.android.gms.policy_ads_fdr_dynamite@223712200@223712200057.473771314.473771314:19)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-506012923:46)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6788)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)</summary>
```

</details>

**Comment by huycozy** [comment]
Hi @hmduc1603, I can not reproduce this issue with [app_open_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/app_open_example). Can you also try and confirm? 
Also, please provide the list of affected device info and the percentage occurrence of the crash. Thanks!
