### ISSUE TITLE
After signing the app Failed to handle method call

### ISSUE THREAD

**Issue by uldongnae** [googleads/googleads-mobile-flutter#738]
**The latest plug-in version was used, and before signing the app, test ads worked fine, but after signing the app, errors started to occur.**
<details>
  <summary>Logs</summary>

```
I/flutter (20831): Ad load failed (code=3 message=No ad config.)
E/MethodChannel#flutter/platform_views(20831): Failed to handle method call
E/MethodChannel#flutter/platform_views(20831): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(20831): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(20831): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(20831): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(20831): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views(20831): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views(20831): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#flutter/platform_views(20831): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(20831): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views(20831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (20831): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/flutter (20831): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
E/flutter (20831): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/flutter (20831): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (20831): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (20831): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (20831): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (20831): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (20831): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (20831): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (20831): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (20831): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (20831): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (20831): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/flutter (20831): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20831): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (20831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (20831): )
E/flutter (20831): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (20831): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (20831): <asynchronous suspension>
E/flutter (20831): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
E/flutter (20831): <asynchronous suspension>
E/flutter (20831): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
E/flutter (20831): <asynchronous suspension>
E/flutter (20831): 
```

</details>

**Comment by uldongnae** [comment]
@huycozy 
yes, errors occur, such as debug / device.
platform -> Android.



`````
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\Desktop\develop\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package net.test signatures do
not match previously installed version; ignoring!]
Uninstalling old version...
Installing build\app\outputs\flutter-apk\app.apk...              2,584ms

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (28445): AppOpenAd failed to load: LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config., responseInfo: ResponseInfo(responseId: null, mediat
ionAdapterClassName: , adapterResponses: [], loadedAdapterResponseInfo: null), responseExtras: {})
I/flutter (28445): FetchLotto
I/flutter (28445): Transition { currentState: LottoListEmpty, event: FetchLotto, nextState: LottoListLoading }
I/flutter (28445): Change { currentState: LottoListEmpty, nextState: LottoListLoading }
I/flutter (28445): Ad load failed (code=3 message=No ad config.)
I/flutter (28445): Transition { currentState: LottoListLoading, event: FetchLotto, nextState: LottoListLoaded }
I/flutter (28445): Change { currentState: LottoListLoading, nextState: LottoListLoaded }
E/flutter (28445): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intVa
lue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/flutter (28445):      at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(Unknown Source:4)
E/flutter (28445):      at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(Unknown Source:79)
E/flutter (28445):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(Unknown Source:232)
E/flutter (28445):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(Unknown Source:175)
E/flutter (28445):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter (28445):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18)
E/flutter (28445):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(Unknown Source:20)
E/flutter (28445):      at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
E/flutter (28445):      at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
E/flutter (28445):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (28445):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (28445):      at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (28445):      at android.os.Looper.loop(Looper.java:288)
E/flutter (28445):      at android.app.ActivityThread.main(ActivityThread.java:7839)
E/flutter (28445):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28445):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (28445):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (28445): )
E/flutter (28445): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter (28445): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
E/flutter (28445): <asynchronous suspension>
E/flutter (28445): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146)
E/flutter (28445): <asynchronous suspension>
E/flutter (28445): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792)
E/flutter (28445): <asynchronous suspension>
E/flutter (28445):

**Comment by huycozy** [comment]
@uldongnae Can you try running on [google_mobile_ads example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and check if it still occurs? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by uldongnae** [comment]
@huycozy 

Since this is an error that occurs in native Ad, the error does not occur in the ad in the example.
I also tried signing the app, but no error occurred.

**Comment by uldongnae** [comment]
Could the error occur depending on the SDK or Gradle version?

**Comment by huycozy** [comment]
@uldongnae Actually the [google_mobile_ads example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) contains NativeAd sample at [reusable_inline_example.dart](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/reusable_inline_example.dart) (in case you may miss it). 

Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
