### ISSUE TITLE
99 crashes in last 7 days, Attempt to invoke virtual method 'int java.lang.Integer.intValue()'

### ISSUE THREAD

**Issue by CodeWithBishal** [googleads/googleads-mobile-flutter#776]
## Plugin Version
google_mobile_ads: ^2.3.0

## Steps to Reproduce

It cannot be reproduced locally.

**Expected results:** 
No Crash

**Actual results:** 
Crash
<details>
  <summary>Logs</summary>

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at io.flutter.plugins.googlemobileads.i0.create(Unknown Source:4)
	at io.flutter.plugin.platform.v$a.p(Unknown Source:51)
	at io.flutter.plugin.platform.v$a.i(Unknown Source:34)
	at t7.k$a.c(Unknown Source:263)
	at t7.k$a.onMethodCall(Unknown Source:175)
	at u7.k$a.a(Unknown Source:17)
	at i7.c.l(Unknown Source:18)
	at i7.c.m(Unknown Source:40)
	at i7.c.i(Unknown Source:0)
	at i7.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.app.ActivityThread.main(ActivityThread.java:8101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at SurfaceAndroidViewController._sendCreateMessage(platform_views.dart:1017)
       at AndroidViewController.create(platform_views.dart:801)
```

### Flutter analyze
```
Analyzing class_12_mock_tests_and_solved_question_papers...             

   info • Do not use BuildContexts across async gaps • google_signin.dart:72:7 • use_build_context_synchronously
   info • 'shareFiles' is deprecated and shouldn't be used. Use shareXFiles instead. • quiz_result.dart:89:17 •
          deprecated_member_use

2 issues found. (ran in 2.1s)

```

### flutter doctor -v

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale
    en-IN)
    • Flutter version 3.7.3 on channel stable at [PATH]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (9 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at [PATH]
    • Platform android-33, build-tools 33.0.0
    • Java binary at: [PATH]
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at [PATH]

[✓] Android Studio (version 2021.3)
    • Android Studio at [PATH]
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at [PATH]
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @CodeWithBishal 
This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/672. Closing this issue as a duplicate, so please follow up on it for further updates.
