### ISSUE TITLE
Crashlytics shows a weird crash report for some devices related to Google ads

### ISSUE THREAD

**Issue by kazeclans** [googleads/googleads-mobile-flutter#881]
This is a rare case crashlytic report being shown for few devices. I would like to know what is the problem here. Is it because of webview or google ads plugin. Device is OnePlus Nord 2t 5g with android 13.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, java.lang.reflect.InvocationTargetException, null, android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1396)
	at n3.b2.B(Unknown Source:76)
	at com.google.android.gms.internal.ads.be0.s(Unknown Source:138)
	at com.google.android.gms.internal.ads.em0.d(Unknown Source:68)
	at com.google.android.gms.internal.ads.em0.e(Unknown Source:12)
	at com.google.android.gms.ads.internal.ClientApi.o5(Unknown Source:6)
	at l3.i.b(Unknown Source:16)
	at l3.u.e(Unknown Source:5)
	at l3.u.d(Unknown Source:79)
	at l3.a3.p(Unknown Source:72)
	at d3.l.b(Unknown Source:59)
	at io.flutter.plugins.googlemobileads.q.e(Unknown Source:60)
	at io.flutter.plugins.googlemobileads.h0.onMethodCall(Unknown Source:952)
	at q9.k$a.a(Unknown Source:17)
	at d9.c.l(Unknown Source:18)
	at d9.c.m(Unknown Source:40)
	at d9.c.i(Unknown Source:0)
	at d9.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
	... 26 more
Caused by: WV.Tb0: errorCode=2
	at WV.SR.f(chromium-SystemWebViewGoogle.aab-beta-579002110:84)
	at WV.SR.g(chromium-SystemWebViewGoogle.aab-beta-579002110:25)
	at org.chromium.android_webview.AwBrowserProcess.i(chromium-SystemWebViewGoogle.aab-beta-579002110:32)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-Syste<truncated: 639 chars>
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at BannerAd.load(ad_containers.dart:895)

**Comment by huycozy** [comment]
Hi @kazeclans 
Based on the stack trace, this crash seems to be reported from native sdk which is wrapped by this plugin. It could be caused by Google play service. 
Moreover, I see there are some reports in google-admob-ads-sdk, see this [filter](https://groups.google.com/g/google-admob-ads-sdk/search?q=InvocationTargetException). So please ask the same question there for more information if any. 

Also, I would suggest you observe the percentage occurrence of the crash to see if it's increasing or only occurs sometime. Then back here with more information that may help us to verify the issue better. Thank you!
