### ISSUE TITLE
PlatformException(error, Unable to find explicit activity class {_/com.google.android.gms.ads.AdActivity};

### ISSUE THREAD

**Issue by Cosminnv** [googleads/googleads-mobile-flutter#974]
I receive random crashes in production saying "PlatformException(error, Unable to find explicit activity class {_/com.google.android.gms.ads.AdActivity};". 
Never personally experienced it in debug or release mode.
I do have integrated native ads (but they are currently disabled so not showing) and interstitial ads (which are enabled and the crash probably involves them)

## Plugin Version

google_mobile_ads: ^3.0.0

## Steps to Reproduce

I cannot reproduce because it happens randomly.
My code is exactly like the example, I initialize MobileAds(without using await) instance in the main function immediately after WidgetsFlutterBinding.ensureInitialized() and the ad gets created in the initState of the first screen. The only difference is that I am first waiting on a response from Remote Config before showing the ad.

I have not declared any activity related to the library in the manifest as this is not shown in the example, the only thing that I declared in the manifest is the application id meta data.

Crashlytics shows this:

io.flutter.plugins.firebase.crashlytics.FlutterError - PlatformException(error, Unable to find explicit activity class {com.denisprojects.healingfrequencies/com.google.android.gms.ads.AdActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-fi

Stacktrace:

```
 Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] eg.i.a(byte[])' on a null object reference
	at dg.a.n(Unknown Source:24)
	at dg.e$b.run(Unknown Source:269)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:240)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:652)
       at MethodChannel._invokeMethod(platform_channel.dart:310)
 ```

Flutter doctor:
![image](https://github.com/googleads/googleads-mobile-flutter/assets/48117967/c30880a0-521e-44b5-b699-121beab5874a)

Crashlytics:
![image](https://github.com/googleads/googleads-mobile-flutter/assets/48117967/e2032b4a-869a-475a-a953-bd72f6f6e6e7)

Most of the crashes happen in background because my app is an audio player but it is still strange because in order for the app to show the ad the user has to manually click a button.

I've had ads for quite some time and this crash was really rare, happening less than 10 times a month, but then lately it's been happening more frequently. (the spike towards the end in the screen is from mostly from a single user that had 100 crashes but you can see that it has generally risen).

Searched only a bit but have not seen much of this issue so I'm probably doing something wrong

**Comment by malandr2** [comment]
Hi @Cosminnv,

This doesn't appear to be related the `google_mobile_ads` plugin but rather an issue in the Android layer. Please create in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) as a next step to address your issue. Thanks.
