### ISSUE TITLE
[google_mobile_ads] [Android only][Exception] an appearance of wired exception when work with any type of ads

### ISSUE THREAD

**Issue by mustafa-707** [googleads/googleads-mobile-flutter#987]
Hello , 

 I'm facing this exception , it not effect the app but still its an EXCEPTION , So this's it : 
 
 ```
 E/Ads     (17308): Couldn't create RTB adapter : 
E/Ads     (17308): android.os.RemoteException
E/Ads     (17308): 	at com.google.android.gms.internal.ads.zzbou.zzc(com.google.android.gms:play-services-ads-lite@@22.5.0:4)
E/Ads     (17308): 	at com.google.android.gms.internal.ads.zzbow.zzbJ(com.google.android.gms:play-services-ads-lite@@22.5.0:8)
E/Ads     (17308): 	at com.google.android.gms.internal.ads.zzaun.onTransact(com.google.android.gms:play-services-ads-base@@22.5.0:3)
E/Ads     (17308): 	at android.os.Binder.transact(Binder.java:628)
E/Ads     (17308): 	at m.ajt.aZ(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:8)
E/Ads     (17308): 	at com.google.android.gms.ads.internal.mediation.client.b.c(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:9)
E/Ads     (17308): 	at com.google.android.gms.ads.nonagon.adapter.e.b(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:5)
E/Ads     (17308): 	at com.google.android.gms.ads.nonagon.signals.ek.a(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:58)
E/Ads     (17308): 	at m.cdv.a(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:3)
E/Ads     (17308): 	at m.cde.run(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:21)
E/Ads     (17308): 	at m.cdx.run(:com.google.android.gms.policy_ads_fdr_dynamite@234310604@234310602023.578924991.578924991:5)
E/Ads     (17308): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)


 ```
 
 I'm using flutter version `3.19.9` , dart  `3.1.5` and `google_mobile_ads` version : `4.0.0`
 
and i tested on the following os :

 android 10 - huawei nova 7i
 android 8 - huawei y7 prime 2019
 pixel 4 - android 12

**Comment by malandr2** [comment]
Hi @mustafa-707,

Given that this stack trace is from the Android platform, this is not something that the google_mobile_ads flutter plugin can address. This can be addressed in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk), please create a thread there with this information for it to be handled appropriately. Closing this issue. Thanks!
